Uberspecific debug on.
***************Entering pref
	SCC: {a11 a19 a20 a22 a28 a3 a33 a36 a4 a40 a49 a52 a53 a54 a56 a60 a64 a9}
	SCC: {a16}
		Father: {a11 a19 a20 a22 a28 a3 a33 a36 a4 a40 a49 a52 a53 a54 a56 a60 a64 a9}
	SCC: {a26}
		Father: {a11 a19 a20 a22 a28 a3 a33 a36 a4 a40 a49 a52 a53 a54 a56 a60 a64 a9}
	SCC: {a14}
		Father: {a11 a19 a20 a22 a28 a3 a33 a36 a4 a40 a49 a52 a53 a54 a56 a60 a64 a9}
	SCC: {a47}
		Father: {a14}
	SCC: {a35}
		Father: {a11 a19 a20 a22 a28 a3 a33 a36 a4 a40 a49 a52 a53 a54 a56 a60 a64 a9}
		Father: {a47}
	SCC: {a45}
		Father: {a11 a19 a20 a22 a28 a3 a33 a36 a4 a40 a49 a52 a53 a54 a56 a60 a64 a9}
	Working on {a11 a19 a20 a22 a28 a3 a33 a36 a4 a40 a49 a52 a53 a54 a56 a60 a64 a9}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O emptied and I filled.
		O: {}
		I: {a11 a19 a20 a22 a28 a3 a33 a36 a4 a40 a49 a52 a53 a54 a56 a60 a64 a9}

	My son! {a11 a19 a20 a22 a28 a3 a33 a36 a4 a40 a49 a52 a53 a54 a56 a60 a64 a9}
	Working on {a16}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a11 a13 a17 a20 a24 a29 a30 a32 a33 a36 a39 a4 a46 a48 a50 a53 a56 a62 a63 a64 a7 a8}
			O preservation not requested
		O: {}
		I: {a16}

	Working on {a26}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a11 a13 a16 a17 a20 a24 a29 a30 a32 a33 a36 a39 a4 a46 a48 a50 a53 a56 a62 a63 a64 a7 a8}
			O added to the optimizationTrack: {}
		O: {}
		I: {a26}

	Working on {a14}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a11 a13 a16 a17 a20 a24 a26 a29 a30 a32 a33 a36 a39 a4 a46 a48 a50 a53 a56 a62 a63 a64 a7 a8}
			O added to the optimizationTrack: {}
		O: {}
		I: {a14}

	My son! {a14}
	Working on {a47}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a11 a13 a14 a16 a17 a20 a24 a26 a29 a30 a32 a33 a36 a39 a4 a46 a48 a50 a53 a56 a62 a63 a64 a7 a8}
			O preservation not requested
		O: {a47}
		I: {}
		Going to call pref.

	My son! {a47}
	Working on {a35}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a11 a13 a14 a16 a17 a20 a24 a26 a29 a30 a32 a33 a36 a39 a4 a46 a48 a50 a53 a56 a62 a63 a64 a7 a8}
			O preservation not requested
		O: {a35}
		I: {}
		Going to call pref.

	Working on {a45}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a11 a13 a14 a16 a17 a20 a24 a26 a29 a30 a32 a33 a36 a39 a4 a46 a48 a50 a53 a56 a62 a63 a64 a7 a8}
			O added to the optimizationTrack: {}
		O: {}
		I: {a45}

***************Exiting pref
Extension 1
{a10 a11 a13 a14 a16 a17 a20 a24 a26 a29 a30 a32 a33 a36 a39 a4 a45 a46 a48 a50 a53 a56 a62 a63 a64 a7 a8}
