Uberspecific debug on.
***************Entering pref
	SCC: {a59 a60}
	SCC: {a61}
		Father: {a59 a60}
	SCC: {a6}
		Father: {a59 a60}
	SCC: {a32}
		Father: {a59 a60}
	SCC: {a1}
		Father: {a59 a60}
	SCC: {a7}
		Father: {a1}
	SCC: {a55}
		Father: {a7}
	SCC: {a2 a20 a29 a3 a38 a44 a5 a50 a8}
		Father: {a59 a60}
		Father: {a6}
		Father: {a55}
	SCC: {a22}
		Father: {a2 a20 a29 a3 a38 a44 a5 a50 a8}
	SCC: {a47}
		Father: {a2 a20 a29 a3 a38 a44 a5 a50 a8}
	SCC: {a35}
		Father: {a2 a20 a29 a3 a38 a44 a5 a50 a8}
	SCC: {a56}
		Father: {a35}
	SCC: {a14 a21}
		Father: {a61}
		Father: {a56}
	SCC: {a27}
		Father: {a7}
		Father: {a2 a20 a29 a3 a38 a44 a5 a50 a8}
		Father: {a47}
	SCC: {a64}
		Father: {a27}
	SCC: {a25}
		Father: {a27}
	SCC: {a57}
		Father: {a6}
		Father: {a64}
		Father: {a25}
	SCC: {a62}
		Father: {a59 a60}
		Father: {a25}
		Father: {a57}
	SCC: {a54}
		Father: {a57}
	SCC: {a45}
		Father: {a1}
		Father: {a35}
		Father: {a14 a21}
	SCC: {a48}
		Father: {a7}
		Father: {a45}
	SCC: {a39}
		Father: {a2 a20 a29 a3 a38 a44 a5 a50 a8}
		Father: {a22}
		Father: {a35}
		Father: {a45}
		Father: {a48}
	SCC: {a17}
		Father: {a2 a20 a29 a3 a38 a44 a5 a50 a8}
		Father: {a14 a21}
		Father: {a45}
	SCC: {a43}
		Father: {a2 a20 a29 a3 a38 a44 a5 a50 a8}
		Father: {a62}
		Father: {a17}
	SCC: {a51}
		Father: {a2 a20 a29 a3 a38 a44 a5 a50 a8}
		Father: {a43}
	SCC: {a12}
		Father: {a62}
		Father: {a51}
	SCC: {a46}
		Father: {a2 a20 a29 a3 a38 a44 a5 a50 a8}
		Father: {a12}
	SCC: {a26}
		Father: {a17}
	Working on {a59 a60}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O emptied and I filled.
		O: {}
		I: {a59 a60}

	My son! {a59 a60}
	Working on {a61}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a19 a28 a30 a40 a41 a53 a59 a63 a9}
			O preservation not requested
		O: {}
		I: {a61}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a19 a28 a30 a40 a41 a53 a60 a63 a9}
			O preservation not requested
		O: {a61}
		I: {}
		Going to call pref.

	Working on {a6}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a19 a28 a30 a40 a41 a53 a59 a61 a63 a9}
			O added to the optimizationTrack: {a6}
		O: {a6}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a19 a28 a30 a40 a41 a53 a60 a63 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a6}

	Working on {a32}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a19 a28 a30 a40 a41 a53 a59 a61 a63 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a32}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a19 a28 a30 a40 a41 a53 a6 a60 a63 a9}
			O added to the optimizationTrack: {a32}
		O: {a32}
		I: {}
		Going to call pref.

	Working on {a1}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a59 a61 a63 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a1}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a19 a28 a30 a40 a41 a53 a6 a60 a63 a9}
			O added to the optimizationTrack: {a1}
		O: {a1}
		I: {}
		Going to call pref.

	My son! {a1}
	Working on {a7}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a59 a61 a63 a9}
			O preservation not requested
		O: {a7}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a19 a28 a30 a40 a41 a53 a6 a60 a63 a9}
			O preservation not requested
		O: {}
		I: {a7}

	My son! {a7}
	Working on {a55}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a59 a61 a63 a9}
			O preservation not requested
		O: {}
		I: {a55}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a19 a28 a30 a40 a41 a53 a6 a60 a63 a7 a9}
			O preservation not requested
		O: {a55}
		I: {}
		Going to call pref.

	My son! {a55}
	Working on {a2 a20 a29 a3 a38 a44 a5 a50 a8}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a55 a59 a61 a63 a9}
			O preservation not requested
		O: {a2 a50}
		I: {a20 a29 a3 a38 a44 a5 a8}
		Going to call pref.
			Calling pref.
***************Entering pref
	SCC: {a20 a29 a3 a38 a44 a5 a8}
	Working on {a20 a29 a3 a38 a44 a5 a8}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O emptied and I filled.
		O: {}
		I: {a20 a29 a3 a38 a44 a5 a8}

***************Exiting pref

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a19 a28 a30 a40 a41 a53 a6 a60 a63 a7 a9}
			O preservation not requested
		O: {a5}
		I: {a2 a20 a29 a3 a38 a44 a50 a8}
		Going to call pref.
			Calling pref.
***************Entering pref
	SCC: {a3 a44 a50}
	SCC: {a2 a20 a29 a38 a8}
		Father: {a3 a44 a50}
	Working on {a3 a44 a50}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O emptied and I filled.
		O: {}
		I: {a3 a44 a50}

	My son! {a3 a44 a50}
	Working on {a2 a20 a29 a38 a8}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {}
			O preservation not requested
		O: {}
		I: {a2 a20 a38 a8}

***************Exiting pref

	My son! {a2 a20 a29 a3 a38 a44 a5 a50 a8}
	Working on {a22}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a55 a59 a61 a63 a9}
			O preservation not requested
		O: {}
		I: {}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a19 a28 a30 a40 a41 a53 a6 a60 a63 a7 a9}
			O preservation not requested
		O: {}
		I: {}

	Working on {a47}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a55 a59 a61 a63 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a19 a28 a30 a40 a41 a53 a6 a60 a63 a7 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

	Working on {a35}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a55 a59 a61 a63 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a19 a28 a30 a40 a41 a53 a6 a60 a63 a7 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

	My son! {a35}
	Working on {a56}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a55 a59 a61 a63 a9}
			O preservation not requested
		O: {}
		I: {}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a19 a28 a30 a40 a41 a53 a6 a60 a63 a7 a9}
			O preservation not requested
		O: {}
		I: {}

	My son! {a56}
	Working on {a14 a21}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a55 a59 a61 a63 a9}
			O preservation not requested
		O: {a14}
		I: {}
		Going to call pref.
			Calling pref.
***************Entering pref
	SCC: {a21}
	Working on {a21}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {}
			O added to the optimizationTrack: {}
		O: {}
		I: {a21}

***************Exiting pref

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a19 a28 a30 a40 a41 a53 a6 a60 a63 a7 a9}
			O preservation not requested
		O: {}
		I: {a14}

	Working on {a27}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a55 a59 a61 a63 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a14 a15 a16 a19 a28 a30 a40 a41 a53 a6 a60 a63 a7 a9}
			O added to the optimizationTrack: {a27}
		O: {a27}
		I: {}
		Going to call pref.

	My son! {a27}
	Working on {a64}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a55 a59 a61 a63 a9}
			O preservation not requested
		O: {}
		I: {}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a14 a15 a16 a19 a28 a30 a40 a41 a53 a6 a60 a63 a7 a9}
			O preservation not requested
		O: {}
		I: {a64}

	Working on {a25}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a55 a59 a61 a63 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a14 a15 a16 a19 a28 a30 a40 a41 a53 a6 a60 a63 a64 a7 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a25}

	My son! {a25}
	Working on {a57}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a55 a59 a61 a63 a9}
			O preservation not requested
		O: {}
		I: {}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a14 a15 a16 a19 a25 a28 a30 a40 a41 a53 a6 a60 a63 a64 a7 a9}
			O preservation not requested
		O: {a57}
		I: {}
		Going to call pref.

	My son! {a57}
	Working on {a62}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a55 a59 a61 a63 a9}
			O preservation not requested
		O: {a62}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a14 a15 a16 a19 a25 a28 a30 a40 a41 a53 a6 a60 a63 a64 a7 a9}
			O preservation not requested
		O: {a62}
		I: {}
		Going to call pref.

	Working on {a54}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a55 a59 a61 a63 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a14 a15 a16 a19 a25 a28 a30 a40 a41 a53 a6 a60 a63 a64 a7 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a54}

	Working on {a45}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a55 a59 a61 a63 a9}
			O added to the optimizationTrack: {a45}
		O: {a45}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a14 a15 a16 a19 a25 a28 a30 a40 a41 a53 a54 a6 a60 a63 a64 a7 a9}
			O added to the optimizationTrack: {a45}
		O: {a45}
		I: {}
		Going to call pref.

	My son! {a45}
	Working on {a48}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a53 a55 a59 a61 a63 a9}
			O preservation not requested
		O: {}
		I: {a48}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a14 a15 a16 a19 a25 a28 a30 a40 a41 a53 a54 a6 a60 a63 a64 a7 a9}
			O preservation not requested
		O: {a48}
		I: {}
		Going to call pref.

	My son! {a48}
	Working on {a39}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a48 a53 a55 a59 a61 a63 a9}
			O preservation not requested
		O: {a39}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a14 a15 a16 a19 a25 a28 a30 a40 a41 a53 a54 a6 a60 a63 a64 a7 a9}
			O preservation not requested
		O: {}
		I: {}

	Working on {a17}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a48 a53 a55 a59 a61 a63 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a14 a15 a16 a19 a25 a28 a30 a40 a41 a53 a54 a6 a60 a63 a64 a7 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

	My son! {a17}
	Working on {a43}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a48 a53 a55 a59 a61 a63 a9}
			O preservation not requested
		O: {}
		I: {}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a14 a15 a16 a19 a25 a28 a30 a40 a41 a53 a54 a6 a60 a63 a64 a7 a9}
			O preservation not requested
		O: {}
		I: {}

	My son! {a43}
	Working on {a51}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a48 a53 a55 a59 a61 a63 a9}
			O preservation not requested
		O: {}
		I: {}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a14 a15 a16 a19 a25 a28 a30 a40 a41 a53 a54 a6 a60 a63 a64 a7 a9}
			O preservation not requested
		O: {}
		I: {}

	My son! {a51}
	Working on {a12}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a48 a53 a55 a59 a61 a63 a9}
			O preservation not requested
		O: {}
		I: {}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a14 a15 a16 a19 a25 a28 a30 a40 a41 a53 a54 a6 a60 a63 a64 a7 a9}
			O preservation not requested
		O: {}
		I: {}

	My son! {a12}
	Working on {a46}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a48 a53 a55 a59 a61 a63 a9}
			O preservation not requested
		O: {}
		I: {}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a14 a15 a16 a19 a25 a28 a30 a40 a41 a53 a54 a6 a60 a63 a64 a7 a9}
			O preservation not requested
		O: {}
		I: {}

	Working on {a26}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a48 a53 a55 a59 a61 a63 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a14 a15 a16 a19 a25 a28 a30 a40 a41 a53 a54 a6 a60 a63 a64 a7 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

***************Exiting pref
Extension 1
{a1 a10 a13 a15 a16 a19 a28 a30 a32 a40 a41 a48 a53 a55 a59 a61 a63 a9}
Extension 2
{a10 a13 a14 a15 a16 a19 a25 a28 a30 a40 a41 a53 a54 a6 a60 a63 a64 a7 a9}
