Uberspecific debug on.
***************Entering pref
	SCC: {a11 a13 a18 a2 a24 a34 a42 a45 a50 a59 a60 a71 a73 a74 a9}
	SCC: {a66}
		Father: {a11 a13 a18 a2 a24 a34 a42 a45 a50 a59 a60 a71 a73 a74 a9}
	SCC: {a53}
		Father: {a11 a13 a18 a2 a24 a34 a42 a45 a50 a59 a60 a71 a73 a74 a9}
	SCC: {a39}
		Father: {a11 a13 a18 a2 a24 a34 a42 a45 a50 a59 a60 a71 a73 a74 a9}
	SCC: {a26}
		Father: {a39}
	SCC: {a20}
		Father: {a39}
	SCC: {a70}
		Father: {a11 a13 a18 a2 a24 a34 a42 a45 a50 a59 a60 a71 a73 a74 a9}
	SCC: {a36}
		Father: {a70}
	SCC: {a16}
		Father: {a11 a13 a18 a2 a24 a34 a42 a45 a50 a59 a60 a71 a73 a74 a9}
	SCC: {a22}
		Father: {a11 a13 a18 a2 a24 a34 a42 a45 a50 a59 a60 a71 a73 a74 a9}
	SCC: {a28}
		Father: {a11 a13 a18 a2 a24 a34 a42 a45 a50 a59 a60 a71 a73 a74 a9}
		Father: {a36}
		Father: {a22}
	SCC: {a10}
		Father: {a11 a13 a18 a2 a24 a34 a42 a45 a50 a59 a60 a71 a73 a74 a9}
		Father: {a70}
		Father: {a28}
	Working on {a11 a13 a18 a2 a24 a34 a42 a45 a50 a59 a60 a71 a73 a74 a9}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O emptied and I filled.
		O: {}
		I: {a11 a13 a18 a2 a24 a34 a42 a45 a50 a59 a60 a71 a73 a74 a9}

	My son! {a11 a13 a18 a2 a24 a34 a42 a45 a50 a59 a60 a71 a73 a74 a9}
	Working on {a66}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a12 a15 a19 a23 a27 a29 a3 a38 a43 a44 a47 a49 a55 a57 a6 a60 a61 a64 a65 a68 a69 a9}
			O preservation not requested
		O: {}
		I: {}

	Working on {a53}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a12 a15 a19 a23 a27 a29 a3 a38 a43 a44 a47 a49 a55 a57 a6 a60 a61 a64 a65 a68 a69 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

	Working on {a39}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a12 a15 a19 a23 a27 a29 a3 a38 a43 a44 a47 a49 a55 a57 a6 a60 a61 a64 a65 a68 a69 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

	My son! {a39}
	Working on {a26}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a12 a15 a19 a23 a27 a29 a3 a38 a43 a44 a47 a49 a55 a57 a6 a60 a61 a64 a65 a68 a69 a9}
			O preservation not requested
		O: {}
		I: {}

	Working on {a20}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a12 a15 a19 a23 a27 a29 a3 a38 a43 a44 a47 a49 a55 a57 a6 a60 a61 a64 a65 a68 a69 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

	Working on {a70}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a12 a15 a19 a23 a27 a29 a3 a38 a43 a44 a47 a49 a55 a57 a6 a60 a61 a64 a65 a68 a69 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

	My son! {a70}
	Working on {a36}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a12 a15 a19 a23 a27 a29 a3 a38 a43 a44 a47 a49 a55 a57 a6 a60 a61 a64 a65 a68 a69 a9}
			O preservation not requested
		O: {}
		I: {}

	Working on {a16}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a12 a15 a19 a23 a27 a29 a3 a38 a43 a44 a47 a49 a55 a57 a6 a60 a61 a64 a65 a68 a69 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

	Working on {a22}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a12 a15 a19 a23 a27 a29 a3 a38 a43 a44 a47 a49 a55 a57 a6 a60 a61 a64 a65 a68 a69 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

	My son! {a22}
	Working on {a28}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a12 a15 a19 a23 a27 a29 a3 a38 a43 a44 a47 a49 a55 a57 a6 a60 a61 a64 a65 a68 a69 a9}
			O preservation not requested
		O: {}
		I: {}

	My son! {a28}
	Working on {a10}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a12 a15 a19 a23 a27 a29 a3 a38 a43 a44 a47 a49 a55 a57 a6 a60 a61 a64 a65 a68 a69 a9}
			O preservation not requested
		O: {}
		I: {}

***************Exiting pref
Extension 1
{a12 a15 a19 a23 a27 a29 a3 a38 a43 a44 a47 a49 a55 a57 a6 a60 a61 a64 a65 a68 a69 a9}
