Uberspecific debug on.
***************Entering pref
	SCC: {a34 a72}
	SCC: {a10}
		Father: {a34 a72}
	SCC: {a56}
		Father: {a10}
	SCC: {a62}
		Father: {a56}
	SCC: {a41}
		Father: {a62}
	SCC: {a40}
		Father: {a62}
	Working on {a34 a72}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O emptied and I filled.
		O: {}
		I: {a34 a72}

	My son! {a34 a72}
	Working on {a10}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a13 a16 a22 a25 a27 a29 a30 a34 a35 a39 a4 a44 a49 a5 a50 a51 a53 a57 a58 a6 a60 a64 a66 a67 a70 a75 a76}
			O preservation not requested
		O: {a10}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a13 a16 a22 a25 a27 a29 a30 a35 a39 a4 a44 a49 a5 a50 a51 a53 a57 a58 a6 a60 a64 a66 a67 a70 a72 a75 a76}
			O preservation not requested
		O: {}
		I: {a10}

	My son! {a10}
	Working on {a56}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a13 a16 a22 a25 a27 a29 a30 a34 a35 a39 a4 a44 a49 a5 a50 a51 a53 a57 a58 a6 a60 a64 a66 a67 a70 a75 a76}
			O preservation not requested
		O: {}
		I: {a56}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a16 a22 a25 a27 a29 a30 a35 a39 a4 a44 a49 a5 a50 a51 a53 a57 a58 a6 a60 a64 a66 a67 a70 a72 a75 a76}
			O preservation not requested
		O: {a56}
		I: {}
		Going to call pref.

	My son! {a56}
	Working on {a62}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a13 a16 a22 a25 a27 a29 a30 a34 a35 a39 a4 a44 a49 a5 a50 a51 a53 a56 a57 a58 a6 a60 a64 a66 a67 a70 a75 a76}
			O preservation not requested
		O: {a62}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a16 a22 a25 a27 a29 a30 a35 a39 a4 a44 a49 a5 a50 a51 a53 a57 a58 a6 a60 a64 a66 a67 a70 a72 a75 a76}
			O preservation not requested
		O: {}
		I: {a62}

	My son! {a62}
	Working on {a41}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a13 a16 a22 a25 a27 a29 a30 a34 a35 a39 a4 a44 a49 a5 a50 a51 a53 a56 a57 a58 a6 a60 a64 a66 a67 a70 a75 a76}
			O preservation not requested
		O: {}
		I: {a41}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a16 a22 a25 a27 a29 a30 a35 a39 a4 a44 a49 a5 a50 a51 a53 a57 a58 a6 a60 a62 a64 a66 a67 a70 a72 a75 a76}
			O preservation not requested
		O: {a41}
		I: {}
		Going to call pref.

	Working on {a40}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a13 a16 a22 a25 a27 a29 a30 a34 a35 a39 a4 a41 a44 a49 a5 a50 a51 a53 a56 a57 a58 a6 a60 a64 a66 a67 a70 a75 a76}
			O added to the optimizationTrack: {}
		O: {}
		I: {a40}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a16 a22 a25 a27 a29 a30 a35 a39 a4 a44 a49 a5 a50 a51 a53 a57 a58 a6 a60 a62 a64 a66 a67 a70 a72 a75 a76}
			O added to the optimizationTrack: {a40}
		O: {a40}
		I: {}
		Going to call pref.

***************Exiting pref
Extension 1
{a13 a16 a22 a25 a27 a29 a30 a34 a35 a39 a4 a40 a41 a44 a49 a5 a50 a51 a53 a56 a57 a58 a6 a60 a64 a66 a67 a70 a75 a76}
Extension 2
{a10 a13 a16 a22 a25 a27 a29 a30 a35 a39 a4 a44 a49 a5 a50 a51 a53 a57 a58 a6 a60 a62 a64 a66 a67 a70 a72 a75 a76}
