Uberspecific debug on.
***************Entering pref
	SCC: {a29 a3 a45}
	SCC: {a30}
		Father: {a29 a3 a45}
	SCC: {a44}
		Father: {a29 a3 a45}
	Working on {a29 a3 a45}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O emptied and I filled.
		O: {}
		I: {a29 a3 a45}

	My son! {a29 a3 a45}
	Working on {a30}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a2 a24 a25 a26 a28 a32 a36 a37 a38 a4 a40 a42 a47 a49 a52 a55 a56 a57 a6 a60 a61 a62 a63 a8}
			O preservation not requested
		O: {}
		I: {}

	Working on {a44}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a2 a24 a25 a26 a28 a32 a36 a37 a38 a4 a40 a42 a47 a49 a52 a55 a56 a57 a6 a60 a61 a62 a63 a8}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

***************Exiting pref
Extension 1
{a1 a2 a24 a25 a26 a28 a32 a36 a37 a38 a4 a40 a42 a47 a49 a52 a55 a56 a57 a6 a60 a61 a62 a63 a8}
