Uberspecific debug on.
***************Entering pref
	SCC: {a47 a59}
	SCC: {a23}
		Father: {a47 a59}
	Working on {a47 a59}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O emptied and I filled.
		O: {}
		I: {a47 a59}

	My son! {a47 a59}
	Working on {a23}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a17 a20 a27 a28 a3 a32 a33 a37 a40 a41 a42 a44 a47 a49 a5 a53 a54 a57 a58 a60 a61 a62 a63 a64 a65 a66}
			O preservation not requested
		O: {}
		I: {a23}

		Going to call boundcond.
			O recalculated.
			e: {a10 a13 a15 a16 a17 a20 a27 a28 a3 a32 a33 a37 a40 a41 a42 a44 a49 a5 a53 a54 a57 a58 a59 a60 a61 a62 a63 a64 a65 a66}
			O preservation not requested
		O: {a23}
		I: {}
		Going to call pref.

***************Exiting pref
Extension 1
{a10 a13 a15 a16 a17 a20 a23 a27 a28 a3 a32 a33 a37 a40 a41 a42 a44 a47 a49 a5 a53 a54 a57 a58 a60 a61 a62 a63 a64 a65 a66}
Extension 2
{a10 a13 a15 a16 a17 a20 a27 a28 a3 a32 a33 a37 a40 a41 a42 a44 a49 a5 a53 a54 a57 a58 a59 a60 a61 a62 a63 a64 a65 a66}
