Uberspecific debug on.
***************Entering pref
	SCC: {a15 a53 a61 a7}
	SCC: {a45}
		Father: {a15 a53 a61 a7}
	SCC: {a9}
		Father: {a45}
	SCC: {a35}
		Father: {a45}
	SCC: {a24}
		Father: {a15 a53 a61 a7}
	SCC: {a25}
		Father: {a24}
	SCC: {a60}
		Father: {a25}
	SCC: {a29}
		Father: {a9}
		Father: {a25}
	SCC: {a52}
		Father: {a29}
	SCC: {a31}
		Father: {a52}
	SCC: {a2 a44}
		Father: {a52}
	SCC: {a62}
		Father: {a2 a44}
	SCC: {a40}
		Father: {a62}
	SCC: {a56}
		Father: {a40}
	SCC: {a20}
		Father: {a56}
	SCC: {a48}
		Father: {a2 a44}
	SCC: {a14}
		Father: {a9}
	SCC: {a32}
		Father: {a14}
	SCC: {a57}
		Father: {a32}
	SCC: {a11}
		Father: {a31}
	SCC: {a10}
		Father: {a35}
	Working on {a15 a53 a61 a7}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O emptied and I filled.
		O: {}
		I: {a15 a53 a61 a7}

	My son! {a15 a53 a61 a7}
	Working on {a45}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a28 a33 a36 a37 a39 a42 a46 a50 a54 a55 a59 a6 a61 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8}
			O preservation not requested
		O: {a45}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a22 a28 a33 a36 a37 a39 a42 a46 a50 a53 a54 a55 a59 a6 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {}
		I: {a45}

	My son! {a45}
	Working on {a9}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a28 a33 a36 a37 a39 a42 a46 a50 a54 a55 a59 a6 a61 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8}
			O preservation not requested
		O: {}
		I: {a9}

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a22 a28 a33 a36 a37 a39 a42 a45 a46 a50 a53 a54 a55 a59 a6 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {a9}
		I: {}
		Going to call pref.

	Working on {a35}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a28 a33 a36 a37 a39 a42 a46 a50 a54 a55 a59 a6 a61 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a35}

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a22 a28 a33 a36 a37 a39 a42 a45 a46 a50 a53 a54 a55 a59 a6 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O added to the optimizationTrack: {a35}
		O: {a35}
		I: {}
		Going to call pref.

	Working on {a24}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a28 a33 a35 a36 a37 a39 a42 a46 a50 a54 a55 a59 a6 a61 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O added to the optimizationTrack: {a24}
		O: {a24}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a22 a28 a33 a36 a37 a39 a42 a45 a46 a50 a53 a54 a55 a59 a6 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O added to the optimizationTrack: {}
		O: {}
		I: {a24}

	My son! {a24}
	Working on {a25}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a28 a33 a35 a36 a37 a39 a42 a46 a50 a54 a55 a59 a6 a61 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O preservation not requested
		O: {}
		I: {a25}

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a22 a24 a28 a33 a36 a37 a39 a42 a45 a46 a50 a53 a54 a55 a59 a6 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {a25}
		I: {}
		Going to call pref.

	My son! {a25}
	Working on {a60}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a25 a28 a33 a35 a36 a37 a39 a42 a46 a50 a54 a55 a59 a6 a61 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O preservation not requested
		O: {a60}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a22 a24 a28 a33 a36 a37 a39 a42 a45 a46 a50 a53 a54 a55 a59 a6 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {}
		I: {a60}

	Working on {a29}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a25 a28 a33 a35 a36 a37 a39 a42 a46 a50 a54 a55 a59 a6 a61 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O added to the optimizationTrack: {a29}
		O: {a29}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a22 a24 a28 a33 a36 a37 a39 a42 a45 a46 a50 a53 a54 a55 a59 a6 a60 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O added to the optimizationTrack: {}
		O: {}
		I: {a29}

	My son! {a29}
	Working on {a52}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a25 a28 a33 a35 a36 a37 a39 a42 a46 a50 a54 a55 a59 a6 a61 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O preservation not requested
		O: {}
		I: {a52}

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a22 a24 a28 a29 a33 a36 a37 a39 a42 a45 a46 a50 a53 a54 a55 a59 a6 a60 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {a52}
		I: {}
		Going to call pref.

	My son! {a52}
	Working on {a31}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a25 a28 a33 a35 a36 a37 a39 a42 a46 a50 a52 a54 a55 a59 a6 a61 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O preservation not requested
		O: {a31}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a22 a24 a28 a29 a33 a36 a37 a39 a42 a45 a46 a50 a53 a54 a55 a59 a6 a60 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {}
		I: {a31}

	Working on {a2 a44}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a25 a28 a33 a35 a36 a37 a39 a42 a46 a50 a52 a54 a55 a59 a6 a61 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O added to the optimizationTrack: {a2}
		O: {a2}
		I: {a44}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a22 a24 a28 a29 a31 a33 a36 a37 a39 a42 a45 a46 a50 a53 a54 a55 a59 a6 a60 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O added to the optimizationTrack: {}
		O: {}
		I: {a2 a44}

	My son! {a2 a44}
	Working on {a62}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a25 a28 a33 a35 a36 a37 a39 a42 a44 a46 a50 a52 a54 a55 a59 a6 a61 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O preservation not requested
		O: {}
		I: {a62}

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a2 a22 a24 a28 a29 a31 a33 a36 a37 a39 a42 a45 a46 a50 a53 a54 a55 a59 a6 a60 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {a62}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a22 a24 a28 a29 a31 a33 a36 a37 a39 a42 a44 a45 a46 a50 a53 a54 a55 a59 a6 a60 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {}
		I: {a62}

	My son! {a62}
	Working on {a40}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a25 a28 a33 a35 a36 a37 a39 a42 a44 a46 a50 a52 a54 a55 a59 a6 a61 a62 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O preservation not requested
		O: {a40}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a2 a22 a24 a28 a29 a31 a33 a36 a37 a39 a42 a45 a46 a50 a53 a54 a55 a59 a6 a60 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {}
		I: {a40}

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a22 a24 a28 a29 a31 a33 a36 a37 a39 a42 a44 a45 a46 a50 a53 a54 a55 a59 a6 a60 a62 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {a40}
		I: {}
		Going to call pref.

	My son! {a40}
	Working on {a56}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a25 a28 a33 a35 a36 a37 a39 a42 a44 a46 a50 a52 a54 a55 a59 a6 a61 a62 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O preservation not requested
		O: {}
		I: {a56}

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a2 a22 a24 a28 a29 a31 a33 a36 a37 a39 a40 a42 a45 a46 a50 a53 a54 a55 a59 a6 a60 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {a56}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a22 a24 a28 a29 a31 a33 a36 a37 a39 a42 a44 a45 a46 a50 a53 a54 a55 a59 a6 a60 a62 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {}
		I: {a56}

	My son! {a56}
	Working on {a20}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a25 a28 a33 a35 a36 a37 a39 a42 a44 a46 a50 a52 a54 a55 a56 a59 a6 a61 a62 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O preservation not requested
		O: {a20}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a2 a22 a24 a28 a29 a31 a33 a36 a37 a39 a40 a42 a45 a46 a50 a53 a54 a55 a59 a6 a60 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {}
		I: {a20}

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a22 a24 a28 a29 a31 a33 a36 a37 a39 a42 a44 a45 a46 a50 a53 a54 a55 a56 a59 a6 a60 a62 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {a20}
		I: {}
		Going to call pref.

	Working on {a48}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a25 a28 a33 a35 a36 a37 a39 a42 a44 a46 a50 a52 a54 a55 a56 a59 a6 a61 a62 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a48}

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a2 a20 a22 a24 a28 a29 a31 a33 a36 a37 a39 a40 a42 a45 a46 a50 a53 a54 a55 a59 a6 a60 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O added to the optimizationTrack: {a48}
		O: {a48}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a22 a24 a28 a29 a31 a33 a36 a37 a39 a42 a44 a45 a46 a50 a53 a54 a55 a56 a59 a6 a60 a62 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O added to the optimizationTrack: {}
		O: {}
		I: {a48}

	Working on {a14}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a25 a28 a33 a35 a36 a37 a39 a42 a44 a46 a48 a50 a52 a54 a55 a56 a59 a6 a61 a62 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O added to the optimizationTrack: {a14}
		O: {a14}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a2 a20 a22 a24 a28 a29 a31 a33 a36 a37 a39 a40 a42 a45 a46 a50 a53 a54 a55 a59 a6 a60 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O added to the optimizationTrack: {}
		O: {}
		I: {a14}

		Going to call boundcond.
			O recalculated.
			e: {a15 a18 a22 a24 a28 a29 a31 a33 a36 a37 a39 a42 a44 a45 a46 a48 a50 a53 a54 a55 a56 a59 a6 a60 a62 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O added to the optimizationTrack: {}
		O: {}
		I: {a14}

	My son! {a14}
	Working on {a32}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a25 a28 a33 a35 a36 a37 a39 a42 a44 a46 a48 a50 a52 a54 a55 a56 a59 a6 a61 a62 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O preservation not requested
		O: {}
		I: {a32}

		Going to call boundcond.
			O recalculated.
			e: {a14 a15 a18 a2 a20 a22 a24 a28 a29 a31 a33 a36 a37 a39 a40 a42 a45 a46 a50 a53 a54 a55 a59 a6 a60 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {a32}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a14 a15 a18 a22 a24 a28 a29 a31 a33 a36 a37 a39 a42 a44 a45 a46 a48 a50 a53 a54 a55 a56 a59 a6 a60 a62 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {a32}
		I: {}
		Going to call pref.

	My son! {a32}
	Working on {a57}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a25 a28 a32 a33 a35 a36 a37 a39 a42 a44 a46 a48 a50 a52 a54 a55 a56 a59 a6 a61 a62 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O preservation not requested
		O: {a57}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a14 a15 a18 a2 a20 a22 a24 a28 a29 a31 a33 a36 a37 a39 a40 a42 a45 a46 a50 a53 a54 a55 a59 a6 a60 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {}
		I: {a57}

		Going to call boundcond.
			O recalculated.
			e: {a14 a15 a18 a22 a24 a28 a29 a31 a33 a36 a37 a39 a42 a44 a45 a46 a48 a50 a53 a54 a55 a56 a59 a6 a60 a62 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O preservation not requested
		O: {}
		I: {a57}

	Working on {a11}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a18 a22 a25 a28 a32 a33 a35 a36 a37 a39 a42 a44 a46 a48 a50 a52 a54 a55 a56 a59 a6 a61 a62 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a11}

		Going to call boundcond.
			O recalculated.
			e: {a14 a15 a18 a2 a20 a22 a24 a28 a29 a31 a33 a36 a37 a39 a40 a42 a45 a46 a50 a53 a54 a55 a57 a59 a6 a60 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O added to the optimizationTrack: {a11}
		O: {a11}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a14 a15 a18 a22 a24 a28 a29 a31 a33 a36 a37 a39 a42 a44 a45 a46 a48 a50 a53 a54 a55 a56 a57 a59 a6 a60 a62 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O added to the optimizationTrack: {a11}
		O: {a11}
		I: {}
		Going to call pref.

	Working on {a10}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a11 a18 a22 a25 a28 a32 a33 a35 a36 a37 a39 a42 a44 a46 a48 a50 a52 a54 a55 a56 a59 a6 a61 a62 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
			O added to the optimizationTrack: {a10}
		O: {a10}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a14 a15 a18 a2 a20 a22 a24 a28 a29 a31 a33 a36 a37 a39 a40 a42 a45 a46 a50 a53 a54 a55 a57 a59 a6 a60 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O added to the optimizationTrack: {}
		O: {}
		I: {a10}

		Going to call boundcond.
			O recalculated.
			e: {a14 a15 a18 a22 a24 a28 a29 a31 a33 a36 a37 a39 a42 a44 a45 a46 a48 a50 a53 a54 a55 a56 a57 a59 a6 a60 a62 a63 a64 a65 a66 a68 a70 a71 a75 a8}
			O added to the optimizationTrack: {}
		O: {}
		I: {a10}

***************Exiting pref
Extension 1
{a11 a18 a22 a25 a28 a32 a33 a35 a36 a37 a39 a42 a44 a46 a48 a50 a52 a54 a55 a56 a59 a6 a61 a62 a63 a64 a65 a66 a68 a7 a70 a71 a75 a8 a9}
Extension 2
{a10 a14 a15 a18 a2 a20 a22 a24 a28 a29 a31 a33 a36 a37 a39 a40 a42 a45 a46 a50 a53 a54 a55 a57 a59 a6 a60 a63 a64 a65 a66 a68 a70 a71 a75 a8}
Extension 3
{a10 a14 a15 a18 a22 a24 a28 a29 a31 a33 a36 a37 a39 a42 a44 a45 a46 a48 a50 a53 a54 a55 a56 a57 a59 a6 a60 a62 a63 a64 a65 a66 a68 a70 a71 a75 a8}
