Uberspecific debug on.
***************Entering pref
	SCC: {a34 a43 a60 a62 a68}
	SCC: {a53}
		Father: {a34 a43 a60 a62 a68}
	SCC: {a69}
		Father: {a34 a43 a60 a62 a68}
		Father: {a53}
	SCC: {a31 a39 a57 a61}
		Father: {a69}
	SCC: {a25}
		Father: {a34 a43 a60 a62 a68}
	SCC: {a22}
		Father: {a34 a43 a60 a62 a68}
	SCC: {a17}
		Father: {a34 a43 a60 a62 a68}
	SCC: {a8}
		Father: {a17}
	SCC: {a44}
		Father: {a8}
	SCC: {a40}
		Father: {a34 a43 a60 a62 a68}
		Father: {a8}
	SCC: {a29}
		Father: {a34 a43 a60 a62 a68}
		Father: {a8}
	SCC: {a16}
		Father: {a40}
	Working on {a34 a43 a60 a62 a68}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O emptied and I filled.
		O: {}
		I: {a34 a43 a60 a62 a68}

	My son! {a34 a43 a60 a62 a68}
	Working on {a53}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a11 a12 a14 a20 a21 a24 a3 a36 a37 a38 a46 a5 a50 a58 a63 a65 a67 a7}
			O preservation not requested
		O: {}
		I: {}

	My son! {a53}
	Working on {a69}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a11 a12 a14 a20 a21 a24 a3 a36 a37 a38 a46 a5 a50 a58 a63 a65 a67 a7}
			O preservation not requested
		O: {}
		I: {}

	My son! {a69}
	Working on {a31 a39 a57 a61}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a11 a12 a14 a20 a21 a24 a3 a36 a37 a38 a46 a5 a50 a58 a63 a65 a67 a7}
			O preservation not requested
		O: {}
		I: {a39 a61}

	Working on {a25}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a11 a12 a14 a20 a21 a24 a3 a36 a37 a38 a39 a46 a5 a50 a58 a61 a63 a65 a67 a7}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

	Working on {a22}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a11 a12 a14 a20 a21 a24 a3 a36 a37 a38 a39 a46 a5 a50 a58 a61 a63 a65 a67 a7}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

	Working on {a17}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a11 a12 a14 a20 a21 a24 a3 a36 a37 a38 a39 a46 a5 a50 a58 a61 a63 a65 a67 a7}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

	My son! {a17}
	Working on {a8}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a11 a12 a14 a20 a21 a24 a3 a36 a37 a38 a39 a46 a5 a50 a58 a61 a63 a65 a67 a7}
			O preservation not requested
		O: {}
		I: {}

	My son! {a8}
	Working on {a44}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a11 a12 a14 a20 a21 a24 a3 a36 a37 a38 a39 a46 a5 a50 a58 a61 a63 a65 a67 a7}
			O preservation not requested
		O: {}
		I: {}

	Working on {a40}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a11 a12 a14 a20 a21 a24 a3 a36 a37 a38 a39 a46 a5 a50 a58 a61 a63 a65 a67 a7}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

	Working on {a29}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a11 a12 a14 a20 a21 a24 a3 a36 a37 a38 a39 a46 a5 a50 a58 a61 a63 a65 a67 a7}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

	Working on {a16}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a11 a12 a14 a20 a21 a24 a3 a36 a37 a38 a39 a46 a5 a50 a58 a61 a63 a65 a67 a7}
			O added to the optimizationTrack: {}
		O: {}
		I: {}

***************Exiting pref
Extension 1
{a1 a11 a12 a14 a20 a21 a24 a3 a36 a37 a38 a39 a46 a5 a50 a58 a61 a63 a65 a67 a7}
