Uberspecific debug on.
***************Entering pref
	SCC: {a12 a7}
	Working on {a12 a7}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O emptied and I filled.
		O: {}
		I: {a12 a7}

***************Exiting pref
Extension 1
{a10 a12 a14 a15 a16 a17 a18 a25 a26 a27 a3 a31 a33 a37 a38 a39 a41 a42 a50 a55 a56 a58 a62 a67 a68 a70 a71 a72 a8}
Extension 2
{a10 a14 a15 a16 a17 a18 a25 a26 a27 a3 a31 a33 a37 a38 a39 a41 a42 a50 a55 a56 a58 a62 a67 a68 a7 a70 a71 a72 a8}
