Uberspecific debug on.
***************Entering pref
	SCC: {a11 a12 a21 a27 a35 a41 a54 a61 a68 a9}
	SCC: {a40}
		Father: {a11 a12 a21 a27 a35 a41 a54 a61 a68 a9}
	SCC: {a26}
		Father: {a40}
	SCC: {a63}
		Father: {a26}
	SCC: {a6}
		Father: {a11 a12 a21 a27 a35 a41 a54 a61 a68 a9}
		Father: {a26}
	SCC: {a57}
		Father: {a11 a12 a21 a27 a35 a41 a54 a61 a68 a9}
	SCC: {a30}
		Father: {a11 a12 a21 a27 a35 a41 a54 a61 a68 a9}
	SCC: {a25}
		Father: {a11 a12 a21 a27 a35 a41 a54 a61 a68 a9}
		Father: {a40}
	SCC: {a49}
		Father: {a11 a12 a21 a27 a35 a41 a54 a61 a68 a9}
	SCC: {a36}
		Father: {a11 a12 a21 a27 a35 a41 a54 a61 a68 a9}
	SCC: {a7}
		Father: {a11 a12 a21 a27 a35 a41 a54 a61 a68 a9}
		Father: {a36}
	Working on {a11 a12 a21 a27 a35 a41 a54 a61 a68 a9}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O emptied and I filled.
		O: {}
		I: {a11 a12 a21 a27 a35 a41 a54 a61 a68 a9}

	My son! {a11 a12 a21 a27 a35 a41 a54 a61 a68 a9}
	Working on {a40}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a11 a13 a17 a23 a28 a3 a32 a34 a41 a42 a44 a46 a54 a59 a60 a61 a65 a67}
			O preservation not requested
		O: {a40}
		I: {}
		Going to call pref.

	My son! {a40}
	Working on {a26}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a11 a13 a17 a23 a28 a3 a32 a34 a41 a42 a44 a46 a54 a59 a60 a61 a65 a67}
			O preservation not requested
		O: {}
		I: {a26}

	My son! {a26}
	Working on {a63}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a11 a13 a17 a23 a26 a28 a3 a32 a34 a41 a42 a44 a46 a54 a59 a60 a61 a65 a67}
			O preservation not requested
		O: {a63}
		I: {}
		Going to call pref.

	Working on {a6}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a11 a13 a17 a23 a26 a28 a3 a32 a34 a41 a42 a44 a46 a54 a59 a60 a61 a65 a67}
			O added to the optimizationTrack: {a6}
		O: {a6}
		I: {}
		Going to call pref.

	Working on {a57}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a11 a13 a17 a23 a26 a28 a3 a32 a34 a41 a42 a44 a46 a54 a59 a60 a61 a65 a67}
			O added to the optimizationTrack: {}
		O: {}
		I: {a57}

	Working on {a30}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a11 a13 a17 a23 a26 a28 a3 a32 a34 a41 a42 a44 a46 a54 a57 a59 a60 a61 a65 a67}
			O added to the optimizationTrack: {}
		O: {}
		I: {a30}

	Working on {a25}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a11 a13 a17 a23 a26 a28 a3 a30 a32 a34 a41 a42 a44 a46 a54 a57 a59 a60 a61 a65 a67}
			O added to the optimizationTrack: {a25}
		O: {a25}
		I: {}
		Going to call pref.

	Working on {a49}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a11 a13 a17 a23 a26 a28 a3 a30 a32 a34 a41 a42 a44 a46 a54 a57 a59 a60 a61 a65 a67}
			O added to the optimizationTrack: {a49}
		O: {a49}
		I: {}
		Going to call pref.

	Working on {a36}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a11 a13 a17 a23 a26 a28 a3 a30 a32 a34 a41 a42 a44 a46 a54 a57 a59 a60 a61 a65 a67}
			O added to the optimizationTrack: {}
		O: {}
		I: {a36}

	My son! {a36}
	Working on {a7}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a10 a11 a13 a17 a23 a26 a28 a3 a30 a32 a34 a36 a41 a42 a44 a46 a54 a57 a59 a60 a61 a65 a67}
			O preservation not requested
		O: {a7}
		I: {}
		Going to call pref.

***************Exiting pref
Extension 1
{a10 a11 a13 a17 a23 a26 a28 a3 a30 a32 a34 a36 a41 a42 a44 a46 a54 a57 a59 a60 a61 a65 a67}
