Uberspecific debug on.
***************Entering pref
	SCC: {a37 a74}
	SCC: {a48}
		Father: {a37 a74}
	SCC: {a56}
		Father: {a48}
	SCC: {a7}
		Father: {a56}
	SCC: {a49}
		Father: {a37 a74}
	SCC: {a54}
		Father: {a49}
	SCC: {a24}
		Father: {a37 a74}
	SCC: {a60}
		Father: {a54}
		Father: {a24}
	SCC: {a27}
		Father: {a60}
	SCC: {a6}
		Father: {a24}
	SCC: {a18}
		Father: {a7}
	SCC: {a28 a8}
		Father: {a18}
	SCC: {a34}
		Father: {a28 a8}
	SCC: {a15 a22 a4 a58 a63 a66}
		Father: {a28 a8}
	SCC: {a69}
		Father: {a37 a74}
		Father: {a15 a22 a4 a58 a63 a66}
	SCC: {a30}
		Father: {a69}
	SCC: {a26}
		Father: {a30}
	SCC: {a13}
		Father: {a15 a22 a4 a58 a63 a66}
	SCC: {a21}
		Father: {a13}
	SCC: {a12}
		Father: {a6}
	SCC: {a36}
		Father: {a34}
		Father: {a12}
	SCC: {a2}
		Father: {a12}
	SCC: {a32}
		Father: {a30}
		Father: {a2}
	SCC: {a19}
		Father: {a2}
	Working on {a37 a74}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O emptied and I filled.
		O: {}
		I: {a37 a74}

	My son! {a37 a74}
	Working on {a48}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a29 a31 a35 a37 a38 a41 a43 a44 a47 a5 a57 a68 a73 a9}
			O preservation not requested
		O: {}
		I: {a48}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a29 a31 a35 a38 a41 a43 a44 a47 a5 a57 a68 a73 a74 a9}
			O preservation not requested
		O: {a48}
		I: {}
		Going to call pref.

	My son! {a48}
	Working on {a56}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a29 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a57 a68 a73 a9}
			O preservation not requested
		O: {a56}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a29 a31 a35 a38 a41 a43 a44 a47 a5 a57 a68 a73 a74 a9}
			O preservation not requested
		O: {}
		I: {a56}

	My son! {a56}
	Working on {a7}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a29 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a57 a68 a73 a9}
			O preservation not requested
		O: {}
		I: {a7}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a29 a31 a35 a38 a41 a43 a44 a47 a5 a56 a57 a68 a73 a74 a9}
			O preservation not requested
		O: {a7}
		I: {}
		Going to call pref.

	Working on {a49}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a29 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a57 a68 a7 a73 a9}
			O added to the optimizationTrack: {a49}
		O: {a49}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a29 a31 a35 a38 a41 a43 a44 a47 a5 a56 a57 a68 a73 a74 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a49}

	My son! {a49}
	Working on {a54}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a29 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a57 a68 a7 a73 a9}
			O preservation not requested
		O: {}
		I: {a54}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a68 a73 a74 a9}
			O preservation not requested
		O: {a54}
		I: {}
		Going to call pref.

	Working on {a24}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a29 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a68 a7 a73 a9}
			O added to the optimizationTrack: {a24}
		O: {a24}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a68 a73 a74 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a24}

	My son! {a24}
	Working on {a60}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a29 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a68 a7 a73 a9}
			O preservation not requested
		O: {a60}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a24 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a68 a73 a74 a9}
			O preservation not requested
		O: {a60}
		I: {}
		Going to call pref.

	My son! {a60}
	Working on {a27}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a29 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a68 a7 a73 a9}
			O preservation not requested
		O: {}
		I: {a27}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a24 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a68 a73 a74 a9}
			O preservation not requested
		O: {}
		I: {a27}

	Working on {a6}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a27 a29 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a68 a7 a73 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a6}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a24 a27 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a68 a73 a74 a9}
			O added to the optimizationTrack: {a6}
		O: {a6}
		I: {}
		Going to call pref.

	Working on {a18}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a27 a29 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a6 a68 a7 a73 a9}
			O added to the optimizationTrack: {a18}
		O: {a18}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a24 a27 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a68 a73 a74 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a18}

	My son! {a18}
	Working on {a28 a8}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a27 a29 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a6 a68 a7 a73 a9}
			O preservation not requested
		O: {}
		I: {a28 a8}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a18 a20 a24 a27 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a68 a73 a74 a9}
			O preservation not requested
		O: {a8}
		I: {a28}
		Going to call pref.

	My son! {a28 a8}
	Working on {a34}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a27 a28 a29 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a6 a68 a7 a73 a9}
			O preservation not requested
		O: {a34}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a27 a29 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a6 a68 a7 a73 a8 a9}
			O preservation not requested
		O: {}
		I: {a34}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a18 a20 a24 a27 a28 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a68 a73 a74 a9}
			O preservation not requested
		O: {a34}
		I: {}
		Going to call pref.

	Working on {a15 a22 a4 a58 a63 a66}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a27 a28 a29 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a6 a68 a7 a73 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a15 a22 a4 a58 a63 a66}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a27 a29 a31 a34 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a6 a68 a7 a73 a8 a9}
			O added to the optimizationTrack: {a22 a63}
		O: {a22 a63}
		I: {a15 a4 a58 a66}
		Going to call pref.
			Calling pref.
***************Entering pref

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a18 a20 a24 a27 a28 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a68 a73 a74 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a15 a22 a4 a58 a63 a66}

	My son! {a15 a22 a4 a58 a63 a66}
	Working on {a69}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a22 a27 a28 a29 a31 a35 a37 a38 a4 a41 a43 a44 a47 a48 a5 a54 a57 a6 a63 a68 a7 a73 a9}
			O preservation not requested
		O: {a69}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a20 a27 a28 a29 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a9}
			O preservation not requested
		O: {a69}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a20 a27 a29 a31 a34 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a8 a9}
			O preservation not requested
		O: {a69}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a18 a20 a22 a24 a27 a28 a29 a31 a35 a38 a4 a41 a43 a44 a47 a49 a5 a56 a57 a63 a68 a73 a74 a9}
			O preservation not requested
		O: {a69}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a18 a20 a24 a27 a28 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a58 a66 a68 a73 a74 a9}
			O preservation not requested
		O: {}
		I: {a69}

	My son! {a69}
	Working on {a30}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a22 a27 a28 a29 a31 a35 a37 a38 a4 a41 a43 a44 a47 a48 a5 a54 a57 a6 a63 a68 a7 a73 a9}
			O preservation not requested
		O: {}
		I: {a30}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a20 a27 a28 a29 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a9}
			O preservation not requested
		O: {}
		I: {a30}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a20 a27 a29 a31 a34 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a8 a9}
			O preservation not requested
		O: {}
		I: {a30}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a18 a20 a22 a24 a27 a28 a29 a31 a35 a38 a4 a41 a43 a44 a47 a49 a5 a56 a57 a63 a68 a73 a74 a9}
			O preservation not requested
		O: {}
		I: {a30}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a18 a20 a24 a27 a28 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a58 a66 a68 a69 a73 a74 a9}
			O preservation not requested
		O: {a30}
		I: {}
		Going to call pref.

	My son! {a30}
	Working on {a26}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a22 a27 a28 a29 a30 a31 a35 a37 a38 a4 a41 a43 a44 a47 a48 a5 a54 a57 a6 a63 a68 a7 a73 a9}
			O preservation not requested
		O: {a26}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a20 a27 a28 a29 a30 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a9}
			O preservation not requested
		O: {a26}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a20 a27 a29 a30 a31 a34 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a8 a9}
			O preservation not requested
		O: {a26}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a18 a20 a22 a24 a27 a28 a29 a30 a31 a35 a38 a4 a41 a43 a44 a47 a49 a5 a56 a57 a63 a68 a73 a74 a9}
			O preservation not requested
		O: {a26}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a18 a20 a24 a27 a28 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a58 a66 a68 a69 a73 a74 a9}
			O preservation not requested
		O: {}
		I: {a26}

	Working on {a13}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a20 a22 a27 a28 a29 a30 a31 a35 a37 a38 a4 a41 a43 a44 a47 a48 a5 a54 a57 a6 a63 a68 a7 a73 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a13}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a20 a27 a28 a29 a30 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a9}
			O added to the optimizationTrack: {a13}
		O: {a13}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a20 a27 a29 a30 a31 a34 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a8 a9}
			O added to the optimizationTrack: {a13}
		O: {a13}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a16 a18 a20 a22 a24 a27 a28 a29 a30 a31 a35 a38 a4 a41 a43 a44 a47 a49 a5 a56 a57 a63 a68 a73 a74 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a13}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a18 a20 a24 a26 a27 a28 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a58 a66 a68 a69 a73 a74 a9}
			O added to the optimizationTrack: {a13}
		O: {a13}
		I: {}
		Going to call pref.

	My son! {a13}
	Working on {a21}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a13 a14 a16 a20 a22 a27 a28 a29 a30 a31 a35 a37 a38 a4 a41 a43 a44 a47 a48 a5 a54 a57 a6 a63 a68 a7 a73 a9}
			O preservation not requested
		O: {a21}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a20 a27 a28 a29 a30 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a9}
			O preservation not requested
		O: {}
		I: {a21}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a20 a27 a29 a30 a31 a34 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a8 a9}
			O preservation not requested
		O: {}
		I: {a21}

		Going to call boundcond.
			O recalculated.
			e: {a1 a13 a14 a16 a18 a20 a22 a24 a27 a28 a29 a30 a31 a35 a38 a4 a41 a43 a44 a47 a49 a5 a56 a57 a63 a68 a73 a74 a9}
			O preservation not requested
		O: {a21}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a18 a20 a24 a26 a27 a28 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a58 a66 a68 a69 a73 a74 a9}
			O preservation not requested
		O: {}
		I: {a21}

	Working on {a12}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a13 a14 a16 a20 a22 a27 a28 a29 a30 a31 a35 a37 a38 a4 a41 a43 a44 a47 a48 a5 a54 a57 a6 a63 a68 a7 a73 a9}
			O added to the optimizationTrack: {a12}
		O: {a12}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a20 a21 a27 a28 a29 a30 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a9}
			O added to the optimizationTrack: {a12}
		O: {a12}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a20 a21 a27 a29 a30 a31 a34 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a8 a9}
			O added to the optimizationTrack: {a12}
		O: {a12}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a13 a14 a16 a18 a20 a22 a24 a27 a28 a29 a30 a31 a35 a38 a4 a41 a43 a44 a47 a49 a5 a56 a57 a63 a68 a73 a74 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a12}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a18 a20 a21 a24 a26 a27 a28 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a58 a66 a68 a69 a73 a74 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a12}

	My son! {a12}
	Working on {a36}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a13 a14 a16 a20 a22 a27 a28 a29 a30 a31 a35 a37 a38 a4 a41 a43 a44 a47 a48 a5 a54 a57 a6 a63 a68 a7 a73 a9}
			O preservation not requested
		O: {}
		I: {a36}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a20 a21 a27 a28 a29 a30 a31 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a9}
			O preservation not requested
		O: {}
		I: {a36}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a20 a21 a27 a29 a30 a31 a34 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a8 a9}
			O preservation not requested
		O: {a36}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a12 a13 a14 a16 a18 a20 a22 a24 a27 a28 a29 a30 a31 a35 a38 a4 a41 a43 a44 a47 a49 a5 a56 a57 a63 a68 a73 a74 a9}
			O preservation not requested
		O: {a36}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a12 a14 a15 a16 a18 a20 a21 a24 a26 a27 a28 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a58 a66 a68 a69 a73 a74 a9}
			O preservation not requested
		O: {a36}
		I: {}
		Going to call pref.

	Working on {a2}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a13 a14 a16 a20 a22 a27 a28 a29 a30 a31 a35 a36 a37 a38 a4 a41 a43 a44 a47 a48 a5 a54 a57 a6 a63 a68 a7 a73 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a2}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a20 a21 a27 a28 a29 a30 a31 a35 a36 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a2}

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a20 a21 a27 a29 a30 a31 a34 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a8 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a2}

		Going to call boundcond.
			O recalculated.
			e: {a1 a12 a13 a14 a16 a18 a20 a22 a24 a27 a28 a29 a30 a31 a35 a38 a4 a41 a43 a44 a47 a49 a5 a56 a57 a63 a68 a73 a74 a9}
			O added to the optimizationTrack: {a2}
		O: {a2}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a12 a14 a15 a16 a18 a20 a21 a24 a26 a27 a28 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a58 a66 a68 a69 a73 a74 a9}
			O added to the optimizationTrack: {a2}
		O: {a2}
		I: {}
		Going to call pref.

	My son! {a2}
	Working on {a32}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a13 a14 a16 a2 a20 a22 a27 a28 a29 a30 a31 a35 a36 a37 a38 a4 a41 a43 a44 a47 a48 a5 a54 a57 a6 a63 a68 a7 a73 a9}
			O preservation not requested
		O: {a32}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a2 a20 a21 a27 a28 a29 a30 a31 a35 a36 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a9}
			O preservation not requested
		O: {a32}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a2 a20 a21 a27 a29 a30 a31 a34 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a8 a9}
			O preservation not requested
		O: {a32}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a12 a13 a14 a16 a18 a20 a22 a24 a27 a28 a29 a30 a31 a35 a38 a4 a41 a43 a44 a47 a49 a5 a56 a57 a63 a68 a73 a74 a9}
			O preservation not requested
		O: {a32}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a12 a14 a15 a16 a18 a20 a21 a24 a26 a27 a28 a29 a31 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a58 a66 a68 a69 a73 a74 a9}
			O preservation not requested
		O: {}
		I: {a32}

	Working on {a19}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O recalculated.
			e: {a1 a13 a14 a16 a2 a20 a22 a27 a28 a29 a30 a31 a35 a36 a37 a38 a4 a41 a43 a44 a47 a48 a5 a54 a57 a6 a63 a68 a7 a73 a9}
			O added to the optimizationTrack: {a19}
		O: {a19}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a2 a20 a21 a27 a28 a29 a30 a31 a35 a36 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a9}
			O added to the optimizationTrack: {a19}
		O: {a19}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a14 a15 a16 a2 a20 a21 a27 a29 a30 a31 a34 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a8 a9}
			O added to the optimizationTrack: {a19}
		O: {a19}
		I: {}
		Going to call pref.

		Going to call boundcond.
			O recalculated.
			e: {a1 a12 a13 a14 a16 a18 a20 a22 a24 a27 a28 a29 a30 a31 a35 a38 a4 a41 a43 a44 a47 a49 a5 a56 a57 a63 a68 a73 a74 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a19}

		Going to call boundcond.
			O recalculated.
			e: {a1 a12 a14 a15 a16 a18 a20 a21 a24 a26 a27 a28 a29 a31 a32 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a58 a66 a68 a69 a73 a74 a9}
			O added to the optimizationTrack: {}
		O: {}
		I: {a19}

***************Exiting pref
Extension 1
{a1 a13 a14 a16 a2 a20 a22 a27 a28 a29 a30 a31 a35 a36 a37 a38 a4 a41 a43 a44 a47 a48 a5 a54 a57 a6 a63 a68 a7 a73 a9}
Extension 2
{a1 a14 a15 a16 a2 a20 a21 a27 a28 a29 a30 a31 a35 a36 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a9}
Extension 3
{a1 a14 a15 a16 a2 a20 a21 a27 a29 a30 a31 a34 a35 a37 a38 a41 a43 a44 a47 a48 a5 a54 a57 a58 a6 a66 a68 a7 a73 a8 a9}
Extension 4
{a1 a12 a13 a14 a16 a18 a19 a20 a22 a24 a27 a28 a29 a30 a31 a35 a38 a4 a41 a43 a44 a47 a49 a5 a56 a57 a63 a68 a73 a74 a9}
Extension 5
{a1 a12 a14 a15 a16 a18 a19 a20 a21 a24 a26 a27 a28 a29 a31 a32 a35 a38 a41 a43 a44 a47 a49 a5 a56 a57 a58 a66 a68 a69 a73 a74 a9}
