Uberspecific debug on.
***************Entering pref
	SCC: {a3 a32}
	Working on {a3 a32}
	New optimizationTrack for the actual SCC
		Going to call boundcond.
			O emptied and I filled.
		O: {}
		I: {a3 a32}

***************Exiting pref
Extension 1
{a15 a19 a2 a20 a21 a25 a27 a28 a29 a3 a31 a37 a38 a39 a4 a42 a44 a45 a48 a49 a50 a51 a52 a56 a59 a61 a63 a7 a9}
Extension 2
{a15 a19 a2 a20 a21 a25 a27 a28 a29 a31 a32 a37 a38 a39 a4 a42 a44 a45 a48 a49 a50 a51 a52 a56 a59 a61 a63 a7 a9}
