SemOpt: Labelling Class Reference
Labelling Class Reference
Class representing a single labelling assignment.
Public Member Functions
Labelling ()
Constructor.
void add_label (Argument *, Label)
Add a new label to this set of labelling.
bool exists_argument_labelling (Argument *)
Check whether an argument is in this labelling or not.
Label get_label (Argument *)
Returns the label of a given argument.
SetArguments * inargs ()
Returns the set of arguments labelled as in
SetArguments * outargs ()
Returns the set of arguments labelled as out
SetArguments * undecargs ()
Returns the set of arguments labelled as undec
bool empty ()
Check whether or not this labelling is empty.
void clone (Labelling *)
Clone this labelling into a new one.
Static Public Attributes
static const Label lab_in = "in"
Label representing an in argument.
static const Label lab_out = "out"
Label representing an out argument.
static const Label lab_undec = "undec"
Label representing an undec argument.
Detailed Description
Class representing a single labelling assignment.
Author
Federico Cerutti feder.nosp@m.ico..nosp@m.cerut.nosp@m.ti@a.nosp@m.cm.or.nosp@m.g
Copyright
GNU Public License v2
Definition at line 14 of file Labelling.h.
Member Function Documentation
void Labelling::add_label (Argument * arg, Label l)
Add a new label to this set of labelling.
Parameters
[in] arg The argument to which this labelling applies
[in] l The label. Valid values for are:
Labelling::lab_in
Labelling::lab_out
Labelling::lab_undec
Definition at line 49 of file Labelling.cpp.
References SetArguments::add_Argument(), lab_in, lab_out, and lab_undec.
Referenced by clone(), Preferred::satlab(), and SymbolicArgumentsSet::toLabelling().
void Labelling::clone (Labelling * other)
Clone this labelling into a new one.
Parameters
[out] other A pointer to a Labelling which will be the clone of this one
Return values
void
Definition at line 121 of file Labelling.cpp.
References add_label().
Referenced by Preferred::prefSAT().
bool Labelling::empty ()
Check whether or not this labelling is empty.
Return values
bool
Definition at line 111 of file Labelling.cpp.
References SetArguments::empty().
Referenced by Preferred::prefSAT().
bool Labelling::exists_argument_labelling (Argument * arg)
Check whether an argument is in this labelling or not.
Parameters
[in] arg A pointer to an Argument
Return values
bool
Definition at line 65 of file Labelling.cpp.
Label Labelling::get_label (Argument * arg)
Returns the label of a given argument.
Parameters
[in] arg A pointer to an argument
Return values
Label
Definition at line 75 of file Labelling.cpp.
SetArguments * Labelling::inargs ()
Returns the set of arguments labelled as in
Return values
SetArguments *
Definition at line 84 of file Labelling.cpp.
Referenced by Preferred::prefSAT(), Preferred::satlab(), and SymbolicArgumentsSet::SymbolicArgumentsSet().
SetArguments * Labelling::outargs ()
Returns the set of arguments labelled as out
Return values
SetArguments *
Definition at line 93 of file Labelling.cpp.
Referenced by Preferred::satlab().
SetArguments * Labelling::undecargs ()
Returns the set of arguments labelled as undec
Return values
SetArguments *
Definition at line 102 of file Labelling.cpp.
Referenced by Preferred::satlab().
The documentation for this class was generated from the following files:
src/Labelling.h
src/Labelling.cpp