SemOpt: SATFormulae Class Reference
SATFormulae Class Reference
Class encompassing a list of OrClause linked by and operators.
Public Member Functions
SATFormulae ()
Simple constructor.
void appendOrClause (OrClause)
Method for appending a new OrClause to the other clause.
void toSS (stringstream *) const
Method for transforming the SAT formulae into a string DIMACS compliant.
void clone (SATFormulae *)
Method for cloning (not coping the pointers) this object into a new one.
int size ()
Method returning the number of OrClause.
bool empty ()
Check if there are no formulae.
Detailed Description
Class encompassing a list of OrClause linked by and operators.
Author
Federico Cerutti f.cer.nosp@m.utti.nosp@m.@abdn.nosp@m..ac..nosp@m.uk
Copyright
GNU Public License v2
Definition at line 19 of file SATFormulae.h.
Member Function Documentation
void SATFormulae::appendOrClause (OrClause c)
Method for appending a new OrClause to the other clause.
Parameters
[in] c The OrClause to append
Return values
void
Definition at line 24 of file SATFormulae.cpp.
void SATFormulae::clone (SATFormulae * newsat)
Method for cloning (not coping the pointers) this object into a new one.
Parameters
[out] newsat A pointer to an initialised SATFormulae() object which will contain the copy of this object
Return values
void
Definition at line 68 of file SATFormulae.cpp.
References SATFormulae(), and size().
bool SATFormulae::empty ()
Check if there are no formulae.
Return values
bool
Definition at line 84 of file SATFormulae.cpp.
int SATFormulae::size ()
Method returning the number of OrClause.
Return values
int The number of OrClause
Definition at line 58 of file SATFormulae.cpp.
Referenced by clone().
void SATFormulae::toSS (stringstream * ss) const
Method for transforming the SAT formulae into a string DIMACS compliant.
Parameters
[out] ss A pointer to a stringstream object already initialised
Return values
void
Definition at line 34 of file SATFormulae.cpp.
The documentation for this class was generated from the following files:
src/SATFormulae.h
src/SATFormulae.cpp