SemOpt: PrecoSat::Mem Class Reference
PrecoSat::Mem Class Reference
#include <precosat.hh>
Public Types
typedef void *(* NewFun)(void *, size_t)
typedef void(* DeleteFun)(void *, void *, size_t)
typedef void *(* ResizeFun)(void *, void *, size_t, size_t)
Public Member Functions
Mem ()
void set (void *e, NewFun n, DeleteFun d, ResizeFun r)
operator size_t () const
size_t getCurrent () const
size_t getMax () const
void * allocate (size_t bytes)
void * callocate (size_t bytes)
void * reallocate (void *ptr, size_t old_bytes, size_t new_bytes)
void * recallocate (void *ptr, size_t o, size_t n)
void deallocate (void *ptr, size_t bytes)
Detailed Description
Definition at line 38 of file precosat.hh.
Member Typedef Documentation
typedef void(* PrecoSat::Mem::DeleteFun)(void *, void *, size_t)
Definition at line 41 of file precosat.hh.
typedef void*(* PrecoSat::Mem::NewFun)(void *, size_t)
Definition at line 40 of file precosat.hh.
typedef void*(* PrecoSat::Mem::ResizeFun)(void *, void *, size_t, size_t)
Definition at line 42 of file precosat.hh.
Constructor & Destructor Documentation
PrecoSat::Mem::Mem () inline
Definition at line 49 of file precosat.hh.
Member Function Documentation
void* PrecoSat::Mem::allocate (size_t bytes) inline
Definition at line 57 of file precosat.hh.
References PrecoSat::die().
Referenced by callocate(), and PrecoSat::Solver::init().
void* PrecoSat::Mem::callocate (size_t bytes) inline
Definition at line 68 of file precosat.hh.
References allocate().
Referenced by PrecoSat::Solver::init().
void PrecoSat::Mem::deallocate (void * ptr, size_t bytes) inline
Definition at line 93 of file precosat.hh.
Referenced by PrecoSat::Stack< PrecoSat::Opt >::release(), and PrecoSat::Solver::reset().
size_t PrecoSat::Mem::getCurrent () const inline
Definition at line 55 of file precosat.hh.
size_t PrecoSat::Mem::getMax () const inline
Definition at line 56 of file precosat.hh.
Referenced by PrecoSat::Solver::prstats().
PrecoSat::Mem::operator size_t () const inline
Definition at line 54 of file precosat.hh.
void* PrecoSat::Mem::reallocate (void * ptr, size_t old_bytes, size_t new_bytes) inline
Definition at line 73 of file precosat.hh.
References PrecoSat::die().
Referenced by recallocate().
void* PrecoSat::Mem::recallocate (void * ptr, size_t o, size_t n) inline
Definition at line 88 of file precosat.hh.
References reallocate().
void PrecoSat::Mem::set (void * e, NewFun n, DeleteFun d, ResizeFun r) inline
Definition at line 50 of file precosat.hh.
Referenced by PrecoSat::Solver::set().
The documentation for this class was generated from the following file:
src/precosat/precosat.hh