SemOpt: SymbolicArgumentsSet Class Reference
SymbolicArgumentsSet Class Reference
Class representing a set of Arguments in a symbolical way.
#include <SymbolicArgumentsSet.h>
Public Member Functions
SymbolicArgumentsSet ()
Simple constructor.
SymbolicArgumentsSet (const SetArguments)
Constructor from a real set of objects.
SymbolicArgumentsSet (const Labelling)
Constructor from a Labelling.
iterator begin () const
Iterator to the begin of this set.
iterator end () const
Iterator to the end of this set.
bool isEmpty () const
Checks whether or not this set is empty.
size_t size () const
Returns the cardinality of this set.
bool exists (const std::string) const
Checks whether an argument exists in this set.
SymbolicArgumentsSet getAttacks (const AF *) const
Returns a new set containing the attack of this set.
SetArguments toSetArguments (const AF *) const
Converts this set in a set containing the real arguments.
Labelling toLabelling (const AF *) const
Converts this set in a Labelling containing the real arguments marked as in.
void add (const std::string)
Adds an element to this set.
void remove (const std::string)
Removes an element from this set.
void clear ()
Removes every element from this set.
SymbolicArgumentsSet intersect (const SymbolicArgumentsSet *) const
Calculates the intersection between the elements of this set and the other.
SymbolicArgumentsSet minus (const SymbolicArgumentsSet *) const
Calculates the difference between the elements of this set and the other.
SymbolicArgumentsSet merge (const SymbolicArgumentsSet *) const
Calculates the union between the elements of this set and the other.
SymbolicArgumentsSet & operator= (const SymbolicArgumentsSet &)
Assignment operator.
bool operator== (const SymbolicArgumentsSet &) const
Equality operator.
Detailed Description
Class representing a set of Arguments in a symbolical way.
(i.e. managing just the names of the arguments).
Author
Maurizio Zucchelli
Version
0.1.0
Date
2013-07-08
Definition at line 26 of file SymbolicArgumentsSet.h.
Constructor & Destructor Documentation
SymbolicArgumentsSet::SymbolicArgumentsSet (const SetArguments source)
Constructor from a real set of objects.
Parameters
[in] source The set to be represented symbolically.
Definition at line 28 of file SymbolicArgumentsSet.cpp.
References SetArguments::begin(), and SetArguments::end().
SymbolicArgumentsSet::SymbolicArgumentsSet (const Labelling source)
Constructor from a Labelling.
The resulting object will contain only the Arguments labelled as "in".
Parameters
[in] source The Labelling to be represented symbolically.
Definition at line 40 of file SymbolicArgumentsSet.cpp.
References SetArguments::begin(), SetArguments::end(), and Labelling::inargs().
Member Function Documentation
void SymbolicArgumentsSet::add (const std::string)
Adds an element to this set.
Parameters
[in] element The name of the element to be added.
Definition at line 181 of file SymbolicArgumentsSet.cpp.
Referenced by Preferred::boundcond(), Preferred::Grounded(), intersect(), and merge().
SymbolicArgumentsSet::iterator SymbolicArgumentsSet::begin () const
Iterator to the begin of this set.
Returns
An iterator pointing at the first of the elements in this set.
Definition at line 63 of file SymbolicArgumentsSet.cpp.
Referenced by Preferred::boundcond(), and Preferred::Grounded().
SymbolicArgumentsSet::iterator SymbolicArgumentsSet::end () const
Iterator to the end of this set.
Returns
An iterator pointing at the last of the elements in this set.
Definition at line 73 of file SymbolicArgumentsSet.cpp.
Referenced by Preferred::boundcond(), and Preferred::Grounded().
bool SymbolicArgumentsSet::exists (const std::string) const
Checks whether an argument exists in this set.
Parameters
[in] element The element to search for.
Returns
true if the element belongs to the set, false otherwise.
Definition at line 107 of file SymbolicArgumentsSet.cpp.
Referenced by Preferred::Grounded(), intersect(), minus(), and AF::restrictTo().
SymbolicArgumentsSet SymbolicArgumentsSet::getAttacks (const AF * theAF) const
Returns a new set containing the attack of this set.
Parameters
[in] theAF The AF containing the description of the attacks of this set.
Returns
A symbolic representation of the attacks of this set.
Definition at line 119 of file SymbolicArgumentsSet.cpp.
Referenced by Preferred::boundcond().
SymbolicArgumentsSet SymbolicArgumentsSet::intersect (const SymbolicArgumentsSet * other) const
Calculates the intersection between the elements of this set and the other.
Parameters
[in] other The other operand.
Returns
A set containing the elements belonging to both the sets.
Definition at line 213 of file SymbolicArgumentsSet.cpp.
References add(), and exists().
Referenced by Preferred::boundcond().
bool SymbolicArgumentsSet::isEmpty () const
Checks whether or not this set is empty.
Returns
true if the set is empty, false otherwise.
Definition at line 85 of file SymbolicArgumentsSet.cpp.
Referenced by Preferred::boundcond(), Preferred::Grounded(), and Preferred::SCCParenthood().
SymbolicArgumentsSet SymbolicArgumentsSet::merge (const SymbolicArgumentsSet * other) const
Calculates the union between the elements of this set and the other.
Parameters
[in] other The other operand.
Returns
A set containing the elements belonging to at least one of the sets.
Definition at line 249 of file SymbolicArgumentsSet.cpp.
References add().
Referenced by Preferred::boundcond(), Preferred::Grounded(), and Preferred::pref().
SymbolicArgumentsSet SymbolicArgumentsSet::minus (const SymbolicArgumentsSet * other) const
Calculates the difference between the elements of this set and the other.
Parameters
[in] other The other operand.
Returns
A set containing the elements belonging to this set but not the other.
Definition at line 231 of file SymbolicArgumentsSet.cpp.
References exists(), and remove().
Referenced by Preferred::boundcond(), and Preferred::Grounded().
SymbolicArgumentsSet & SymbolicArgumentsSet::operator= (const SymbolicArgumentsSet & other)
Assignment operator.
Parameters
[in] other The set source of the assignment.
Returns
A reference to this set, now a copy of the other one.
Definition at line 266 of file SymbolicArgumentsSet.cpp.
bool SymbolicArgumentsSet::operator== (const SymbolicArgumentsSet & other) const
Equality operator.
Parameters
[in] other The other operand.
Returns
true if the two sets have the same elements, false otherwise.
Definition at line 280 of file SymbolicArgumentsSet.cpp.
void SymbolicArgumentsSet::remove (const std::string)
Removes an element from this set.
Parameters
[in] element The name of the element to be removed.
Definition at line 191 of file SymbolicArgumentsSet.cpp.
Referenced by minus().
size_t SymbolicArgumentsSet::size () const
Returns the cardinality of this set.
Returns
The number of elements in this set.
Definition at line 95 of file SymbolicArgumentsSet.cpp.
Labelling SymbolicArgumentsSet::toLabelling (const AF * theAF) const
Converts this set in a Labelling containing the real arguments marked as in.
Parameters
[in] theAF The AF with the real elements of this set.
Returns
A Labelling containing the elements of the AF indexed by this set marked as in.
Definition at line 155 of file SymbolicArgumentsSet.cpp.
References Labelling::add_label(), and Labelling::lab_in.
SetArguments SymbolicArgumentsSet::toSetArguments (const AF * theAF) const
Converts this set in a set containing the real arguments.
Parameters
[in] theAF The AF with the real elements of this set.
Returns
A set containing the elements of the AF indexed by this set.
Definition at line 131 of file SymbolicArgumentsSet.cpp.
References SetArguments::add_Argument().
The documentation for this class was generated from the following files:
src/SymbolicArgumentsSet.h
src/SymbolicArgumentsSet.cpp