SemOpt: PrecoSat::Heap< T, L > Class Template Reference
PrecoSat::Heap< T, L > Class Template Reference
#include <precosat.hh>
Public Member Functions
void release (Mem &mem)
operator int () const
T * operator[] (int i)
bool contains (T *e) const
void up (T *e)
void down (T *e)
void check ()
void construct ()
T * max ()
void push (Mem &mem, T *e)
T * pop ()
void remove (T *e)
void fix (ptrdiff_t diff)
Detailed Description
template<class T, class L>
class PrecoSat::Heap< T, L >
Definition at line 159 of file precosat.hh.
Member Function Documentation
template<class T, class L> void PrecoSat::Heap< T, L >::check () inline
Definition at line 207 of file precosat.hh.
Referenced by PrecoSat::Heap< PrecoSat::Rnk, PrecoSat::Hotter >::construct().
template<class T, class L> void PrecoSat::Heap< T, L >::construct () inline
Definition at line 224 of file precosat.hh.
template<class T, class L> bool PrecoSat::Heap< T, L >::contains (T * e) const inline
Definition at line 173 of file precosat.hh.
Referenced by PrecoSat::Heap< PrecoSat::Rnk, PrecoSat::Hotter >::down(), PrecoSat::Heap< PrecoSat::Rnk, PrecoSat::Hotter >::push(), and PrecoSat::Heap< PrecoSat::Rnk, PrecoSat::Hotter >::remove().
template<class T, class L> void PrecoSat::Heap< T, L >::down (T * e) inline
Definition at line 185 of file precosat.hh.
Referenced by PrecoSat::Heap< PrecoSat::Rnk, PrecoSat::Hotter >::construct(), PrecoSat::Heap< PrecoSat::Rnk, PrecoSat::Hotter >::pop(), and PrecoSat::Heap< PrecoSat::Rnk, PrecoSat::Hotter >::remove().
template<class T, class L> void PrecoSat::Heap< T, L >::fix (ptrdiff_t diff) inline
Definition at line 270 of file precosat.hh.
template<class T, class L> T* PrecoSat::Heap< T, L >::max () inline
Definition at line 230 of file precosat.hh.
template<class T, class L> PrecoSat::Heap< T, L >::operator int () const inline
Definition at line 171 of file precosat.hh.
template<class T, class L> T* PrecoSat::Heap< T, L >::operator[] (int i) inline
Definition at line 172 of file precosat.hh.
template<class T, class L> T* PrecoSat::Heap< T, L >::pop () inline
Definition at line 237 of file precosat.hh.
template<class T, class L> void PrecoSat::Heap< T, L >::push (Mem & mem, T * e) inline
Definition at line 231 of file precosat.hh.
template<class T, class L> void PrecoSat::Heap< T, L >::release (Mem & mem) inline
Definition at line 170 of file precosat.hh.
template<class T, class L> void PrecoSat::Heap< T, L >::remove (T * e) inline
Definition at line 253 of file precosat.hh.
template<class T, class L> void PrecoSat::Heap< T, L >::up (T * e) inline
Definition at line 174 of file precosat.hh.
Referenced by PrecoSat::Heap< PrecoSat::Rnk, PrecoSat::Hotter >::push(), and PrecoSat::Heap< PrecoSat::Rnk, PrecoSat::Hotter >::remove().
The documentation for this class was generated from the following file:
src/precosat/precosat.hh