SemOpt: Preferred Class Reference
Preferred Class Reference
Class used to generate the preferred extensions.
Public Member Functions
Preferred ()
Simple constructor.
virtual ~Preferred ()
Simple destructor.
void prefSAT (AF *, SetArguments *)
Method to generate the Preferred Extensions.
void pref (AF *, SetArguments *)
Main resolutive function.
void pref (AF *, SymbolicArgumentsSet *)
Main resolutive function.
iterator begin ()
Begin of the iterator for the preferred extension.
iterator end ()
End of the iterator for the preferred extension.
Private Member Functions
int compute_new_pigreek ()
Method for filling in the attribute sat_new_pigreek.
bool satlab (SATFormulae, Labelling *)
Method for deriving a labelling from a SAT Formulae.
void cleanlabs ()
Method to clean the labels.
void boundcond (SCC *, SymbolicArgumentsSet *, SymbolicArgumentsSet *, SymbolicArgumentsSet *)
Function boundcond.
list< SCC * > SCCSSEQ ()
SCC sequence finder.
int TarjanAlg (DFSNode *, list< SCC * > *, stack< DFSNode * > *, int)
Tarjan Algorithm for SCC determination.
void Grounded (const SymbolicArgumentsSet *, SymbolicArgumentsSet *, SymbolicArgumentsSet *)
Function to calculate the grounded extensions.
void SCCParenthood (list< SCC * > *)
Function to determine the parenthood between SCCs.
void initDFSAF ()
Initialization of the support structure for DFS (called in constructor)
bool stackSearch (stack< DFSNode * >, DFSNode *)
Searches for an element in a stack.
DFSNode * searchArgument (Argument *)
Searches the DFSNode corresponding to the given Argument in DFSAF.
Private Attributes
AF * af
The Argumentation Framework considered.
SetArguments * C
the set of arguments to consider
Detailed Description
Class used to generate the preferred extensions.
Author
geryo
Mattia Rizzini
Maurizio Zucchelli
Date
2013-06-10
2013-06-25
Definition at line 42 of file Preferred.h.
Member Function Documentation
Preferred::iterator Preferred::begin ()
Begin of the iterator for the preferred extension.
Returns
An iterator pointing at the first element of the preferred extension
Definition at line 398 of file Preferred.cpp.
Referenced by initDFSAF(), pref(), SCCParenthood(), and TarjanAlg().
void Preferred::boundcond (SCC * aSCC, SymbolicArgumentsSet * e, SymbolicArgumentsSet * O, SymbolicArgumentsSet * I) private
Function boundcond.
If called with non-empty O, only I is calculated and O is kept as-is.
Parameters
[in] aSCC The Strongly Connected Component to consider.
[in] e The actual extension.
[out] O First output set.
[out] I Second output set. Must be empty.
Definition at line 24 of file Preferred_boundcond.cpp.
References SymbolicArgumentsSet::add(), af, SymbolicArgumentsSet::begin(), SymbolicArgumentsSet::end(), AF::get_arguments(), SymbolicArgumentsSet::getAttacks(), SymbolicArgumentsSet::intersect(), SymbolicArgumentsSet::isEmpty(), SymbolicArgumentsSet::merge(), and SymbolicArgumentsSet::minus().
Referenced by pref().
Preferred::iterator Preferred::end ()
End of the iterator for the preferred extension.
Returns
An iterator pointing at the last element of the preferred extension
Definition at line 409 of file Preferred.cpp.
Referenced by initDFSAF(), pref(), SCCParenthood(), and TarjanAlg().
void Preferred::Grounded (const SymbolicArgumentsSet * theC, SymbolicArgumentsSet * e, SymbolicArgumentsSet * I) private
Function to calculate the grounded extensions.
Calculates the set containing every argument which, if used, ensures to win the argument and the set of nodes which can be used on both sides
Parameters
[in] theC The subset of arguments to consider.
[out] e The extension
[out] I The set of the indolent arguments
Definition at line 24 of file Preferred_Grounded.cpp.
References SymbolicArgumentsSet::add(), af, SymbolicArgumentsSet::begin(), C, SymbolicArgumentsSet::end(), SymbolicArgumentsSet::exists(), Argument::get_attackers(), Argument::get_attacks(), AF::getArgumentByName(), SymbolicArgumentsSet::isEmpty(), SymbolicArgumentsSet::merge(), and SymbolicArgumentsSet::minus().
Referenced by pref().
void Preferred::pref (AF * theAF, SetArguments * theC)
Main resolutive function.
Fills the labels of the class with the preferred extensions found.
This version just calls pref with theC as a SymbolicArgumentsSet instead of a SetArguments.
Parameters
[in] theAF The AF to be considered
[in] theC The subset of Arguments to consider
Definition at line 21 of file Preferred_pref.cpp.
Referenced by pref().
void Preferred::pref (AF * theAF, SymbolicArgumentsSet * theC)
Main resolutive function.
Fills the labels of the class with the preferred extensions found.
Parameters
[in] theAF The AF to be considered
[in] theC The subset of Arguments to consider
Definition at line 34 of file Preferred_pref.cpp.
References af, begin(), boundcond(), cleanlabs(), end(), AF::get_arguments(), Grounded(), initDFSAF(), SymbolicArgumentsSet::merge(), pref(), Preferred(), prefSAT(), AF::restrictTo(), SCCSSEQ(), and AF::toString().
void Preferred::prefSAT (AF * the_af, SetArguments * the_c)
Method to generate the Preferred Extensions.
Parameters
[in] the_af The AF on which calculate the extensions
[in] the_c The subset of arguments to consider
Definition at line 293 of file Preferred.cpp.
References af, SATFormulae::appendOrClause(), OrClause::appendVariable(), SetArguments::begin(), C, SetArguments::cardinality(), cleanlabs(), SATFormulae::clone(), Labelling::clone(), compute_new_pigreek(), Labelling::empty(), SetArguments::end(), Argument::getName(), Labelling::inargs(), satlab(), and SetArguments::setminus().
Referenced by pref().
bool Preferred::satlab (SATFormulae sat, Labelling * lab) private
Method for deriving a labelling from a SAT Formulae.
This method is a wrapper for a SAT Solver
Parameters
[in] sat The SATFormulae as input
[out] sat The computed Labelling
Return values
bool true if a solution is found, false otherwise
Definition at line 233 of file Preferred.cpp.
References Labelling::add_label(), af, SetArguments::cardinality(), AF::getArgumentByNumber(), Argument::getName(), Labelling::inargs(), Labelling::lab_in, Labelling::lab_out, Labelling::lab_undec, AF::numArgs(), Labelling::outargs(), SATFormulae::size(), SATFormulae::toSS(), and Labelling::undecargs().
Referenced by prefSAT().
void Preferred::SCCParenthood (list< SCC * > * SCCList) private
Function to determine the parenthood between SCCs.
Parameters
SCC
Definition at line 53 of file Preferred_sccsseq.cpp.
References af, begin(), end(), and SymbolicArgumentsSet::isEmpty().
Referenced by SCCSSEQ().
list< SCC * > Preferred::SCCSSEQ () private
SCC sequence finder.
Returns
A list containing the sets of Strongly Connected Components found by the algorithm
Definition at line 16 of file Preferred_sccsseq.cpp.
References SCCParenthood(), and TarjanAlg().
Referenced by pref().
Preferred::DFSNode * Preferred::searchArgument (Argument * node) private
Searches the DFSNode corresponding to the given Argument in DFSAF.
Parameters
node The Argument to search for
Definition at line 193 of file Preferred_sccsseq.cpp.
Referenced by TarjanAlg().
bool Preferred::stackSearch (stack< DFSNode * > s, DFSNode * node) private
Searches for an element in a stack.
Parameters
s The stack to search in
node The DFSNode to search for
Definition at line 164 of file Preferred_sccsseq.cpp.
Referenced by TarjanAlg().
int Preferred::TarjanAlg (DFSNode * node, list< SCC * > * SCCList, stack< DFSNode * > * s, int index) private
Tarjan Algorithm for SCC determination.
Parameters
node The Node for which the argument is executed
SCC The list of SCCs found
s A temporal stack containing the actual SCC
index An integer containing the level actually visited
Returns
The updated index, containing the last level visited.
Definition at line 76 of file Preferred_sccsseq.cpp.
References begin(), end(), searchArgument(), and stackSearch().
Referenced by SCCSSEQ().
The documentation for this class was generated from the following files:
src/Preferred.h
src/Preferred.cpp
src/Preferred_boundcond.cpp
src/Preferred_Grounded.cpp
src/Preferred_pref.cpp
src/Preferred_sccsseq.cpp