SemOpt: PrecoSat::Stack< T > Class Template Reference
PrecoSat::Stack< T > Class Template Reference
#include <precosat.hh>
Public Member Functions
size_t bytes () const
Stack ()
~Stack ()
operator int () const
void push (Mem &m, const T &d)
const T & pop ()
const T & top ()
T & operator[] (int i)
void shrink (int m=0)
void shrink (T *nt)
void release (Mem &m)
const T * begin () const
const T * end () const
T * begin ()
T * end ()
void remove (const T &d)
void trymove (const T &d)
Detailed Description
template<class T>
class PrecoSat::Stack< T >
Definition at line 103 of file precosat.hh.
Constructor & Destructor Documentation
template<class T> PrecoSat::Stack< T >::Stack () inline
Definition at line 120 of file precosat.hh.
template<class T> PrecoSat::Stack< T >::~Stack () inline
Definition at line 121 of file precosat.hh.
Member Function Documentation
template<class T> const T* PrecoSat::Stack< T >::begin () const inline
Definition at line 130 of file precosat.hh.
Referenced by PrecoSat::Heap< PrecoSat::Rnk, PrecoSat::Hotter >::fix(), and PrecoSat::Solver::satisfied().
template<class T> T* PrecoSat::Stack< T >::begin () inline
Definition at line 132 of file precosat.hh.
template<class T> size_t PrecoSat::Stack< T >::bytes () const inline
Definition at line 107 of file precosat.hh.
Referenced by PrecoSat::Stack< PrecoSat::Opt >::release().
template<class T> const T* PrecoSat::Stack< T >::end () const inline
Definition at line 131 of file precosat.hh.
Referenced by PrecoSat::Heap< PrecoSat::Rnk, PrecoSat::Hotter >::fix(), and PrecoSat::Solver::satisfied().
template<class T> T* PrecoSat::Stack< T >::end () inline
Definition at line 133 of file precosat.hh.
template<class T> PrecoSat::Stack< T >::operator int () const inline
Definition at line 122 of file precosat.hh.
template<class T> T& PrecoSat::Stack< T >::operator[] (int i) inline
Definition at line 126 of file precosat.hh.
template<class T> const T& PrecoSat::Stack< T >::pop () inline
Definition at line 124 of file precosat.hh.
template<class T> void PrecoSat::Stack< T >::push (Mem & m, const T & d) inline
Definition at line 123 of file precosat.hh.
Referenced by PrecoSat::Solver::add(), and PrecoSat::Heap< PrecoSat::Rnk, PrecoSat::Hotter >::push().
template<class T> void PrecoSat::Stack< T >::release (Mem & m) inline
Definition at line 129 of file precosat.hh.
Referenced by PrecoSat::Heap< PrecoSat::Rnk, PrecoSat::Hotter >::release(), PrecoSat::Solver::reset(), and PrecoSat::Sorter< T, L >::~Sorter().
template<class T> void PrecoSat::Stack< T >::remove (const T & d) inline
Definition at line 134 of file precosat.hh.
template<class T> void PrecoSat::Stack< T >::shrink (int m = 0) inline
Definition at line 127 of file precosat.hh.
Referenced by PrecoSat::Heap< PrecoSat::Rnk, PrecoSat::Hotter >::pop(), and PrecoSat::Heap< PrecoSat::Rnk, PrecoSat::Hotter >::remove().
template<class T> void PrecoSat::Stack< T >::shrink (T * nt) inline
Definition at line 128 of file precosat.hh.
template<class T> const T& PrecoSat::Stack< T >::top () inline
Definition at line 125 of file precosat.hh.
template<class T> void PrecoSat::Stack< T >::trymove (const T & d) inline
Definition at line 147 of file precosat.hh.
The documentation for this class was generated from the following file:
src/precosat/precosat.hh