SemOpt: Semantics Class Reference
Semantics Class Reference
General class for a semantics for an AF.
Public Member Functions
Semantics (AF *, int)
Constructor for the Semantics.
Protected Member Functions
int complete_labelling_SAT_constraints ()
Method for filling in the attribute sat_pigreek.
bool satlab (SATFormulae, Labelling *)
Method for deriving a labelling from a SAT Formulae.
void cleanlabs ()
Clean the labellings.
Protected Attributes
AF * af
The Argumentation Framework considered.
int encoding
The chosen encoding.
SATFormulae sat_pigreek
The Sat Formulae as described in TAFA-13 filled in by the constructor Semantics::Semantics.
vector< Labelling > labellings
Attribute that contains the computed extensions.
Detailed Description
General class for a semantics for an AF.
Author
Federico Cerutti feder.nosp@m.ico..nosp@m.cerut.nosp@m.ti@a.nosp@m.cm.or.nosp@m.g
Copyright
GNU Public License v2
Definition at line 16 of file Semantics.h.
Constructor & Destructor Documentation
Semantics::Semantics (AF * the_af, int enc)
Constructor for the Semantics.
Parameters
[in] the_af The pointer to the object instance of AF which represents the argumentation framework
[in] enc An int representing the type of encoding desired according to the given table
encoding Chosen encodings according to TAFA-13
0
1
2
3
4
5
Definition at line 244 of file Semantics.cpp.
References af, complete_labelling_SAT_constraints(), encoding, labellings, and sat_pigreek.
Member Function Documentation
int Semantics::complete_labelling_SAT_constraints () protected
Method for filling in the attribute sat_pigreek.
Called by the constructor Semantics::Semantics
Definition at line 24 of file Semantics.cpp.
References OrClause::addHeadVariable(), af, SATFormulae::appendOrClause(), OrClause::appendVariable(), AF::begin(), SetArguments::begin(), OrClause::clone(), debug, SetArguments::empty(), encoding, AF::end(), SetArguments::end(), sat_pigreek, and SATFormulae::size().
Referenced by Semantics().
bool Semantics::satlab (SATFormulae sat, Labelling * lab) protected
Method for deriving a labelling from a SAT Formulae.
This method is a wrapper for a SAT Solver
Parameters
[in] sat The SATFormulae as input
[out] sat The computed Labelling
Return values
bool true if a solution is found, false otherwise
Definition at line 177 of file Semantics.cpp.
References Labelling::add_label(), af, SetArguments::cardinality(), debug, AF::getArgumentByNumber(), Argument::getName(), Labelling::inargs(), Labelling::lab_in, Labelling::lab_out, Labelling::lab_undec, AF::numArgs(), Labelling::outargs(), SATFormulae::size(), SATFormulae::toSS(), and Labelling::undecargs().
Referenced by PreferredSemantics::compute_depht_first().
Member Data Documentation
int Semantics::encoding protected
The chosen encoding.
See Also
Semantics::Semantics
Definition at line 20 of file Semantics.h.
Referenced by complete_labelling_SAT_constraints(), and Semantics().
The documentation for this class was generated from the following files:
src/Semantics.h
src/Semantics.cpp