SemOpt: PrecoSat::Solver Class Reference
PrecoSat::Solver Class Reference
#include <precosat.hh>
Public Member Functions
Solver ()
void set (void *e, Mem::NewFun n, Mem::DeleteFun d, Mem::ResizeFun r)
void setprfx (const char *newprfx)
bool set (const char *option, int arg)
bool set (const char *o, const char *a)
void set (FILE *file)
void init (int initial_maxvar=0)
void fxopts ()
void add (int lit)
int next ()
int solve (int decision_limit=INT_MAX)
int val (int l)
Val fixed (int lit) const
double seconds ()
bool satisfied ()
void prstats ()
void propts ()
void reset ()
int getMaxVar () const
int getAddedOrigClauses () const
operator bool () const
Friends
class Progress
Detailed Description
Definition at line 525 of file precosat.hh.
Constructor & Destructor Documentation
PrecoSat::Solver::Solver () inline
Definition at line 747 of file precosat.hh.
Member Function Documentation
void PrecoSat::Solver::add (int lit) inline
Definition at line 760 of file precosat.hh.
References PrecoSat::Stack< T >::push().
Referenced by mainPrecosat(), and precosat_lib().
Val Solver::fixed (int lit) const inline
Definition at line 376 of file precosat.cc.
References PrecoSat::Var::dlevel.
void Solver::fxopts ()
Definition at line 913 of file precosat.cc.
References PrecoSat::Opts::autark, PrecoSat::Opts::block, PrecoSat::Opts::decompose, PrecoSat::Opts::dominate, PrecoSat::Opts::dynred, PrecoSat::Opts::elim, PrecoSat::Opts::fixed, PrecoSat::Opts::merge, PrecoSat::Opts::minimize, PrecoSat::Opts::otfs, PrecoSat::Opts::plain, PrecoSat::Opts::probe, PrecoSat::Opts::random, and PrecoSat::Opts::rebias.
Referenced by mainPrecosat(), and precosat_lib().
int PrecoSat::Solver::getAddedOrigClauses () const inline
Definition at line 771 of file precosat.hh.
References PrecoSat::Stats::clauses, and PrecoSat::Stats::oadd.
int PrecoSat::Solver::getMaxVar () const inline
Definition at line 770 of file precosat.hh.
void Solver::init (int initial_maxvar = 0)
Definition at line 683 of file precosat.cc.
References PrecoSat::Mem::allocate(), block, PrecoSat::Mem::callocate(), elim, PrecoSat::Cls::lits, PrecoSat::Cls::MAXGLUE, OPT, and PrecoSat::Opts::set().
Referenced by mainPrecosat(), and precosat_lib().
int PrecoSat::Solver::next () inline
Definition at line 761 of file precosat.hh.
PrecoSat::Solver::operator bool () const inline
Definition at line 772 of file precosat.hh.
void Solver::propts ()
Definition at line 932 of file precosat.cc.
References PrecoSat::Opts::fixed, and PrecoSat::Opts::printoptions().
Referenced by mainPrecosat().
void Solver::prstats ()
Definition at line 938 of file precosat.cc.
References PrecoSat::Stats::added, PrecoSat::Stats::all, PrecoSat::Stats::assumed, PrecoSat::Stats::asym, PrecoSat::Stats::autark, PrecoSat::Stats::autarks, PrecoSat::Stats::back, PrecoSat::Stats::blkd, PrecoSat::Stats::blocked, PrecoSat::Stats::bw, PrecoSat::Stats::clauses, PrecoSat::Stats::collected, PrecoSat::Stats::conflicts, PrecoSat::Stats::count, PrecoSat::Stats::cuts, PrecoSat::Stats::decisions, PrecoSat::Stats::deleted, PrecoSat::Stats::depth, PrecoSat::Stats::dh, PrecoSat::Stats::dist, PrecoSat::Stats::doms, PrecoSat::Stats::dyn, PrecoSat::Stats::elim, PrecoSat::Stats::enlarged, PrecoSat::Stats::equiv, PrecoSat::Stats::expl, PrecoSat::Stats::extend, PrecoSat::Stats::failed, PrecoSat::Stats::fixed, PrecoSat::Stats::flipped, PrecoSat::Stats::forced, PrecoSat::Stats::fw, PrecoSat::Stats::gc, PrecoSat::Stats::gcautark, PrecoSat::Stats::gcpure, PrecoSat::Mem::getMax(), PrecoSat::Stats::glue, PrecoSat::Stats::impl, PrecoSat::Stats::inverse, PrecoSat::Stats::iter, PrecoSat::Stats::jump, PrecoSat::Stats::level1, PrecoSat::Stats::lifted, PrecoSat::Stats::lits, PrecoSat::Stats::merged, PrecoSat::Stats::mins, PrecoSat::Stats::nontriv, PrecoSat::Stats::org, PrecoSat::Stats::orig, PrecoSat::Stats::otfs, PrecoSat::Stats::phases, PrecoSat::Stats::probe, PrecoSat::Stats::probing, PrecoSat::Stats::props, PrecoSat::Stats::pure, PrecoSat::Stats::random, PrecoSat::Stats::rebias, PrecoSat::Stats::red, PrecoSat::Stats::reductions, PrecoSat::Stats::res, PrecoSat::Stats::rescored, PrecoSat::Stats::restart, PrecoSat::Stats::rounds, PrecoSat::Stats::sccs, PrecoSat::Stats::seconds(), PrecoSat::Stats::shrunken, PrecoSat::Stats::sigs, PrecoSat::Stats::simp, PrecoSat::Stats::simps, PrecoSat::Stats::simptime, PrecoSat::Stats::size, PrecoSat::Stats::skipped, PrecoSat::Stats::slimmed, PrecoSat::Stats::srch, PrecoSat::Stats::srchtime, PrecoSat::Stats::stat, PrecoSat::Stats::str, PrecoSat::Stats::strong, PrecoSat::Stats::subs, PrecoSat::Stats::subst, PrecoSat::Stats::ternaryvisits, PrecoSat::Stats::track, PrecoSat::Stats::variables, PrecoSat::Stats::vars, PrecoSat::Opts::verbose, PrecoSat::Stats::visits, and PrecoSat::Stats::zombies.
Referenced by mainPrecosat().
void Solver::reset ()
Definition at line 857 of file precosat.cc.
References PrecoSat::Mem::deallocate(), PrecoSat::Opts::glue, PrecoSat::Opts::opts, and PrecoSat::Stack< T >::release().
Referenced by mainPrecosat().
bool Solver::satisfied ()
Definition at line 1968 of file precosat.cc.
References PrecoSat::Stack< T >::begin(), PrecoSat::Stack< T >::end(), and PrecoSat::Opts::glue.
double PrecoSat::Solver::seconds () inline
Definition at line 765 of file precosat.hh.
References PrecoSat::Stats::seconds().
Referenced by mainPrecosat().
void PrecoSat::Solver::set (void * e, Mem::NewFun n, Mem::DeleteFun d, Mem::ResizeFun r) inline
Definition at line 749 of file precosat.hh.
References PrecoSat::Mem::set().
Referenced by mainPrecosat(), and precosat_lib().
bool PrecoSat::Solver::set (const char * option, int arg) inline
Definition at line 753 of file precosat.hh.
References PrecoSat::Opts::set().
bool PrecoSat::Solver::set (const char * o, const char * a) inline
Definition at line 754 of file precosat.hh.
References PrecoSat::Opts::set().
void PrecoSat::Solver::set (FILE * file) inline
Definition at line 755 of file precosat.hh.
void PrecoSat::Solver::setprfx (const char * newprfx) inline
Definition at line 752 of file precosat.hh.
int Solver::solve (int decision_limit = INT_MAX)
Definition at line 4992 of file precosat.cc.
References PrecoSat::Opts::output, PrecoSat::Opts::print, and PrecoSat::Stats::simps.
Referenced by mainPrecosat(), and precosat_lib().
int PrecoSat::Solver::val (int l) inline
Definition at line 763 of file precosat.hh.
Referenced by mainPrecosat(), and precosat_lib().
Friends And Related Function Documentation
friend class Progress friend
Definition at line 658 of file precosat.hh.
Member Data Documentation
void Solver::block inline
Definition at line 535 of file precosat.hh.
Referenced by init().
bool Solver::decide
Definition at line 535 of file precosat.hh.
void Solver::elim
Definition at line 535 of file precosat.hh.
Referenced by init().
The documentation for this class was generated from the following files:
src/precosat/precosat.hh
src/precosat/precosat.cc