SemOpt: PreferredSemantics Class Reference
PreferredSemantics Class Reference
Class for the preferred semantics for an AF.
Public Member Functions
PreferredSemantics (AF *the_af, int enc)
void compute_depht_first ()
This is the function that in TAFA-13 is described by Algorithm 1.
void compute ()
Computing semantics extensions.
Public Member Functions inherited from CompleteSemantics
CompleteSemantics (AF *the_af, int enc)
Public Member Functions inherited from Semantics
Semantics (AF *, int)
Constructor for the Semantics.
Additional Inherited Members
Protected Member Functions inherited from Semantics
int complete_labelling_SAT_constraints ()
Method for filling in the attribute sat_pigreek.
bool satlab (SATFormulae, Labelling *)
Method for deriving a labelling from a SAT Formulae.
void cleanlabs ()
Clean the labellings.
Protected Attributes inherited from Semantics
AF * af
The Argumentation Framework considered.
int encoding
The chosen encoding.
SATFormulae sat_pigreek
The Sat Formulae as described in TAFA-13 filled in by the constructor Semantics::Semantics.
vector< Labelling > labellings
Attribute that contains the computed extensions.
Detailed Description
Class for the preferred semantics for an AF.
Author
Federico Cerutti feder.nosp@m.ico..nosp@m.cerut.nosp@m.ti@a.nosp@m.cm.or.nosp@m.g
Copyright
GNU Public License v2
Definition at line 13 of file PreferredSemantics.h.
Constructor & Destructor Documentation
PreferredSemantics::PreferredSemantics (AF * the_af, int enc)
See Also
CompleteSemantics::CompleteSemantics
Definition at line 25 of file PreferredSemantics.cpp.
Member Function Documentation
void PreferredSemantics::compute_depht_first ()
This is the function that in TAFA-13 is described by Algorithm 1.
This function has been rewritten for adhering to Algorithm 1 of TAFA-13, but the one used for the empirical evaluation in TAFA-13 was slightly different as it adopts some straightforward optimisations
Definition at line 70 of file PreferredSemantics.cpp.
References Semantics::af, SATFormulae::appendOrClause(), OrClause::appendVariable(), SetArguments::begin(), SetArguments::cardinality(), Semantics::cleanlabs(), SATFormulae::clone(), Labelling::clone(), debug, Labelling::empty(), SetArguments::end(), Argument::getName(), Labelling::inargs(), Semantics::labellings, AF::numArgs(), Labelling::outargs(), Semantics::sat_pigreek, Semantics::satlab(), and Labelling::undecargs().
Referenced by main().
The documentation for this class was generated from the following files:
src/PreferredSemantics.h
src/PreferredSemantics.cpp