SemOpt: Argument Class Reference
Argument Class Reference
Class representing an Argument.
Public Member Functions
Argument (string, int, AF *)
Constructor.
string getName () const
Method returning the name of the argument.
int getNumber () const
Method returning the unique integer identifier of this argument.
AF * get_af ()
Method returning the AF to which this argument belongs.
Variable InVar ()
Method for determining a propositional variable representing that this argument should be labelled as IN
Variable OutVar ()
Method for determining a propositional variable representing that this argument should be labelled as OUT
Variable UndecVar ()
Method for determining a propositional variable representing that this argument should be labelled as UNDEC
Variable NotInVar ()
Method for determining the negation of the propositional variable representing that this argument should be labelled as IN
Variable NotOutVar ()
Method for determining the negation of the propositional variable representing that this argument should be labelled as OUT
Variable NotUndecVar ()
Method for determining the negation of the propositional variable representing that this argument should be labelled as UNDEC
bool operator== (const Argument &other) const
Overloading of the == operator.
bool operator!= (const Argument &other) const
Overloading of the != operator.
void add_attacks (Argument *)
Method for adding an attacks originated from this argument.
void add_attackers (Argument *)
Method for adding an attacker.
SetArguments * get_attacks ()
Method returning the set of attackers.
SetArguments * get_attackers ()
Method returning the set of attacked arguments.
Detailed Description
Class representing an Argument.
Author
Federico Cerutti f.cer.nosp@m.utti.nosp@m.@abdn.nosp@m..ac..nosp@m.uk
Copyright
GNU Public License v2
Definition at line 30 of file Argument.h.
Constructor & Destructor Documentation
Argument::Argument (string name, int num, AF * theaf)
Constructor.
Parameters
[in] name The name of the argument. It must be unique
[in] num A number identifying this argument. It must be unique
[in] theaf The pointer to the Argumentation Framework to which this argument belongs
Definition at line 17 of file Argument.cpp.
Member Function Documentation
void Argument::add_attackers (Argument * arg)
Method for adding an attacker.
Parameters
[in] arg
Return values
void
Definition at line 152 of file Argument.cpp.
References SetArguments::add_Argument().
void Argument::add_attacks (Argument * arg)
Method for adding an attacks originated from this argument.
Parameters
[in] arg
Return values
void
Definition at line 142 of file Argument.cpp.
References SetArguments::add_Argument().
Referenced by AF::readFile().
AF * Argument::get_af ()
Method returning the AF to which this argument belongs.
Return values
AF*
Definition at line 179 of file Argument.cpp.
SetArguments * Argument::get_attackers ()
Method returning the set of attacked arguments.
Return values
SetArguments*
Definition at line 170 of file Argument.cpp.
Referenced by Preferred::Grounded(), and AF::restrictTo().
SetArguments * Argument::get_attacks ()
Method returning the set of attackers.
Return values
SetArguments*
Definition at line 161 of file Argument.cpp.
Referenced by Preferred::Grounded(), and AF::restrictTo().
string Argument::getName () const
Method returning the name of the argument.
Return values
string
Definition at line 35 of file Argument.cpp.
Referenced by SetArguments::add_Argument(), SetArguments::exists(), operator!=(), operator==(), Preferred::prefSAT(), SetArguments::remove(), and Preferred::satlab().
int Argument::getNumber () const
Method returning the unique integer identifier of this argument.
Return values
int
Definition at line 44 of file Argument.cpp.
Referenced by SetArguments::add_Argument(), operator!=(), and operator==().
Variable Argument::InVar ()
Method for determining a propositional variable representing that this argument should be labelled as IN
Return values
Variable
Definition at line 54 of file Argument.cpp.
Referenced by NotInVar().
Variable Argument::NotInVar ()
Method for determining the negation of the propositional variable representing that this argument should be labelled as IN
Return values
Variable
Definition at line 84 of file Argument.cpp.
References InVar().
Variable Argument::NotOutVar ()
Method for determining the negation of the propositional variable representing that this argument should be labelled as OUT
Return values
Variable
Definition at line 94 of file Argument.cpp.
References OutVar().
Variable Argument::NotUndecVar ()
Method for determining the negation of the propositional variable representing that this argument should be labelled as UNDEC
Return values
Variable
Definition at line 104 of file Argument.cpp.
References UndecVar().
bool Argument::operator!= (const Argument & other) const
Overloading of the != operator.
Parameters
[in] other The other term of the comparison
Return values
bool
Definition at line 128 of file Argument.cpp.
References getName(), and getNumber().
bool Argument::operator== (const Argument & other) const
Overloading of the == operator.
Parameters
[in] other The other term of the comparison
Return values
bool
Definition at line 114 of file Argument.cpp.
References getName(), and getNumber().
Variable Argument::OutVar ()
Method for determining a propositional variable representing that this argument should be labelled as OUT
Return values
Variable
Definition at line 64 of file Argument.cpp.
References AF::numArgs().
Referenced by NotOutVar().
Variable Argument::UndecVar ()
Method for determining a propositional variable representing that this argument should be labelled as UNDEC
Return values
Variable
Definition at line 74 of file Argument.cpp.
References AF::numArgs().
Referenced by NotUndecVar().
The documentation for this class was generated from the following files:
src/Argument.h
src/Argument.cpp