SemOpt: PrecoSat Namespace Reference
PrecoSat Namespace Reference
Classes
class Progress
struct LitScore
struct FreeVarsLt
class Sorter
class Mem
class Stack
class Heap
struct Anchor
struct Rnk
struct Hotter
struct Var
struct Cls
struct Frame
struct GateStats
struct Stats
struct Limit
struct Opt
struct Opts
struct SCC
class RNG
struct Occ
struct Occs
class Solver
Typedefs
typedef signed char Val
typedef enum Vrt Vrt
typedef Stack< Cls * > Orgs
typedef Stack< Cls * > Fwds
Enumerations
enum Vrt {
FREE = 0, ZOMBIE = 1, PURE = 2, AUTARK = 3,
ELIM = 4, EQUIV = 5, FIXED = 6
}
Functions
int ulit2ilit (int u)
void die (const char *,...)
template<class A , class E >
void dequeue (A &anchor, E *e)
template<class A , class E >
bool connected (A &anchor, E *e)
template<class A , class E >
void push (A &anchor, E *e)
template<class A , class E >
void enqueue (A &anchor, E *e)
template<class A , class E >
void mtf (A &a, E *e)
Typedef Documentation
typedef Stack<Cls*> PrecoSat::Fwds
Definition at line 523 of file precosat.hh.
typedef Stack<Cls*> PrecoSat::Orgs
Definition at line 522 of file precosat.hh.
typedef signed char PrecoSat::Val
Definition at line 337 of file precosat.hh.
typedef enum Vrt PrecoSat::Vrt
Definition at line 349 of file precosat.hh.
Enumeration Type Documentation
enum PrecoSat::Vrt
Enumerator
FREE
ZOMBIE
PURE
AUTARK
ELIM
EQUIV
FIXED
Definition at line 339 of file precosat.hh.
Function Documentation
template<class A , class E > bool PrecoSat::connected (A & anchor, E * e)
Definition at line 288 of file precosat.hh.
template<class A , class E > void PrecoSat::dequeue (A & anchor, E * e)
Definition at line 277 of file precosat.hh.
Referenced by mtf().
void PrecoSat::die (const char * msg, ...)
Definition at line 5039 of file precosat.cc.
Referenced by PrecoSat::Mem::allocate(), mainPrecosat(), precosat_lib(), and PrecoSat::Mem::reallocate().
template<class A , class E > void PrecoSat::enqueue (A & anchor, E * e)
Definition at line 305 of file precosat.hh.
template<class A , class E > void PrecoSat::mtf (A & a, E * e)
Definition at line 315 of file precosat.hh.
References dequeue(), and push().
template<class A , class E > void PrecoSat::push (A & anchor, E * e)
Definition at line 295 of file precosat.hh.
Referenced by mtf().
int PrecoSat::ulit2ilit (int u)
Definition at line 127 of file precosat.cc.