SemOpt: src/SemOpt.cpp File Reference
SemOpt.cpp File Reference
Main file.
#include "semopt.h"
Functions
int main (int argc, char *argv[])
Main.
Variables
bool debug = false
Configuration variables.
Detailed Description
Main file.
Author
Federico Cerutti f.cer.nosp@m.utti.nosp@m.@abdn.nosp@m..ac..nosp@m.uk and Mauro Vallati m.val.nosp@m.lati.nosp@m.@hud..nosp@m.ac.u.nosp@m.k
Copyright
GNU Public License v2
Definition in file SemOpt.cpp.
Function Documentation
int main (int argc, char * argv[])
Main.
Return values
int The return value can be:
-127: Missing parameters
-1: Unable to parse the AF file
-126: Something goes wrong
-125: Wrong SAT Solver
0: SUCCESS!!!
Definition at line 38 of file SemOpt.cpp.
References GroundedSemantics::compute(), StableSemantics::compute(), SemistableSemantics::compute(), PreferredSemantics::compute(), CompleteSemantics::compute(), PreferredSemantics::compute_depht_first(), GroundedSemantics::compute_poly(), parseParams(), AF::readFile(), and showHelp().