SemOpt: PrecoSat::Cls Struct Reference
PrecoSat::Cls Struct Reference
#include <precosat.hh>
Public Member Functions
size_t bytes () const
Cls (int l0=0, int l1=0, int l2=0)
int minlit () const
bool contains (int) const
void print (const char *prefix="") const
Static Public Member Functions
static size_t bytes (int n)
Public Attributes
bool locked:1
bool lnd:1
bool garbage:1
bool binary:1
bool trash:1
bool dirty:1
bool gate:1
bool str:1
bool fresh:1
bool freed:1
bool glued:1
unsigned glue:LDMAXGLUE
unsigned size:LDMAXSZ
unsigned sig
Cls * prev
Cls * next
int lits [4]
Static Public Attributes
static const unsigned LDMAXGLUE = 4
static const unsigned MAXGLUE = (1<<LDMAXGLUE)-1
static const int LDMAXSZ = 32 - 9 - LDMAXGLUE
static const int MAXSZ = (1<<LDMAXSZ)-1
Detailed Description
Definition at line 361 of file precosat.hh.
Constructor & Destructor Documentation
PrecoSat::Cls::Cls (int l0 = 0, int l1 = 0, int l2 = 0) inline
Definition at line 373 of file precosat.hh.
References lits.
Referenced by bytes().
Member Function Documentation
size_t Cls::bytes (int n) inline static
Definition at line 269 of file precosat.cc.
References Cls().
size_t Cls::bytes () const inline
Definition at line 273 of file precosat.cc.
bool Cls::contains (int lit) const inline
Definition at line 289 of file precosat.cc.
References lits, and sig.
int Cls::minlit () const inline
Definition at line 282 of file precosat.cc.
References lits.
void Cls::print (const char * prefix = "") const
Definition at line 5104 of file precosat.cc.
Member Data Documentation
bool PrecoSat::Cls::binary
Definition at line 364 of file precosat.hh.
bool PrecoSat::Cls::dirty
Definition at line 364 of file precosat.hh.
bool PrecoSat::Cls::freed
Definition at line 365 of file precosat.hh.
bool PrecoSat::Cls::fresh
Definition at line 365 of file precosat.hh.
bool PrecoSat::Cls::garbage
Definition at line 363 of file precosat.hh.
bool PrecoSat::Cls::gate
Definition at line 365 of file precosat.hh.
unsigned PrecoSat::Cls::glue
Definition at line 368 of file precosat.hh.
bool PrecoSat::Cls::glued
Definition at line 367 of file precosat.hh.
const unsigned PrecoSat::Cls::LDMAXGLUE = 4 static
Definition at line 362 of file precosat.hh.
const int PrecoSat::Cls::LDMAXSZ = 32 - 9 - LDMAXGLUE static
Definition at line 366 of file precosat.hh.
int PrecoSat::Cls::lits[4]
Definition at line 370 of file precosat.hh.
Referenced by Cls(), contains(), PrecoSat::Solver::init(), and minlit().
bool PrecoSat::Cls::lnd
Definition at line 363 of file precosat.hh.
bool PrecoSat::Cls::locked
Definition at line 363 of file precosat.hh.
const unsigned PrecoSat::Cls::MAXGLUE = (1<<LDMAXGLUE)-1 static
Definition at line 362 of file precosat.hh.
Referenced by PrecoSat::Solver::init().
const int PrecoSat::Cls::MAXSZ = (1<<LDMAXSZ)-1 static
Definition at line 366 of file precosat.hh.
Cls * PrecoSat::Cls::next
Definition at line 369 of file precosat.hh.
Cls* PrecoSat::Cls::prev
Definition at line 369 of file precosat.hh.
unsigned PrecoSat::Cls::sig
Definition at line 368 of file precosat.hh.
Referenced by contains().
unsigned PrecoSat::Cls::size
Definition at line 368 of file precosat.hh.
bool PrecoSat::Cls::str
Definition at line 365 of file precosat.hh.
bool PrecoSat::Cls::trash
Definition at line 364 of file precosat.hh.
The documentation for this struct was generated from the following files:
src/precosat/precosat.hh
src/precosat/precosat.cc