/**********************************************************/
/* Automatically generated by './mkconfig': do note edit! */
/**********************************************************/
#define PRECOSAT_CXX "g++ (Ubuntu/Linaro 4.7.3-1ubuntu1) 4.7.3"
#define PRECOSAT_CXXFLAGS "-O3 -static -Wall -Wextra -DNDEBUG -DNLOGPRECO -DNSTATSPRECO $(PROF)"
#define PRECOSAT_OS "Linux DeeperBlack 3.8.0-19-generic x86_64"
#define PRECOSAT_COMPILED "lun 24 giu 2013, 14.38.28, CEST"
#define PRECOSAT_RELEASED "Thu Jan 12 07:59:44 CET 2012"
#define PRECOSAT_VERSION "576"
#define PRECOSAT_ID "7e5e66faa15ff83953915cba4b46afe851cd5847"
